import { createHash } from 'node:crypto'
import { mkdir, mkdtemp, readFile, realpath, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join, relative, sep } from 'node:path'

import { describe, expect, it } from 'vitest'

import { applyPlan } from '../../src/applier/apply-plan.js'
import type { VirtualArtifact } from '../../src/domain/artifacts.js'
import { createChangePlan } from '../../src/planner/create-plan.js'

const owner = '@agent-policy/agent-policy-toolkit'
const toolkitVersion = '0.1.0-alpha.0'

function hash(content: string): string {
  return createHash('sha256').update(content, 'utf8').digest('hex')
}

function generated(path: string, body: string): VirtualArtifact {
  const content = `<!--\nGenerated by ${owner}.\n-->\n${body}`
  return { path, content, sha256: hash(content), owner, operation: 'replace' }
}

async function sandbox(): Promise<{ readonly parent: string; readonly root: string }> {
  const parent = await mkdtemp(join(tmpdir(), 'agent-policy-path-contract-'))
  const root = join(parent, 'consumer')
  await mkdir(root)
  return { parent, root }
}

function outside(root: string, candidate: string): boolean {
  const offset = relative(root, candidate)
  return offset === '..' || offset.startsWith(`..${sep}`)
}

describe('cross-platform path and confinement contracts', () => {
  it.each([
    ['nested\\escape.md', 'Windows separator'],
    ['C:\\escape.md', 'Windows absolute path'],
    ['../escape.md', 'parent traversal'],
    ['safe/../../escape.md', 'nested traversal'],
  ])('rejects %s (%s) before saving a plan', async (unsafePath) => {
    const { parent, root } = await sandbox()
    await expect(createChangePlan({
      command: 'update',
      toolkitVersion,
      repositoryRoot: root,
      planPath: join(parent, 'unsafe-plan.json'),
      desiredArtifacts: [generated(unsafePath, 'must not be written\n')],
      createdAt: '2026-08-13T00:00:00.000Z',
    })).rejects.toThrow(/artifact path/i)
  })

  it('retains case and Unicode distinctions in canonical POSIX plan paths', async () => {
    const { parent, root } = await sandbox()
    const reviewed = await createChangePlan({
      command: 'update',
      toolkitVersion,
      repositoryRoot: root,
      planPath: join(parent, 'case-unicode-plan.json'),
      desiredArtifacts: [
        generated('./Case/Name.md', 'upper-case path\n'),
        generated('case/name.md', 'lower-case path\n'),
        generated('данные/é.md', 'composed Unicode path\n'),
        generated('данные/cafe\u0301.md', 'decomposed Unicode path\n'),
      ],
      createdAt: '2026-08-13T00:00:00.000Z',
    })

    expect(reviewed.desiredArtifacts.map(({ path }) => path)).toEqual([
      'Case/Name.md',
      'case/name.md',
      'данные/cafe\u0301.md',
      'данные/é.md',
    ])
    expect(reviewed.desiredArtifacts.every(({ path }) => !path.includes('\\'))).toBe(true)
  })

  it('writes through a confined in-repository symlink and never resolves outside root', async () => {
    const { parent, root } = await sandbox()
    const actual = join(root, 'actual')
    const linked = join(root, 'linked')
    await mkdir(actual)
    await symlink(actual, linked)
    const reviewed = await createChangePlan({
      command: 'update',
      toolkitVersion,
      repositoryRoot: root,
      planPath: join(parent, 'symlink-plan.json'),
      desiredArtifacts: [generated('linked/данные/result.md', 'confined Unicode output\n')],
      createdAt: '2026-08-13T00:00:00.000Z',
    })

    await expect(applyPlan(reviewed, { repositoryRoot: root, toolkitVersion })).resolves.toMatchObject({ ok: true })
    const actualFile = join(actual, 'данные/result.md')
    expect(await readFile(actualFile, 'utf8')).toBe('<!--\nGenerated by @agent-policy/agent-policy-toolkit.\n-->\nconfined Unicode output\n')
    expect(outside(await realpath(root), await realpath(actualFile))).toBe(false)
  })

  it('rejects a symlink escape before creating or applying a reviewed plan', async () => {
    const { parent, root } = await sandbox()
    const outsideRoot = join(parent, 'outside')
    await mkdir(outsideRoot)
    await symlink(outsideRoot, join(root, 'linked'))

    await expect(createChangePlan({
      command: 'update',
      toolkitVersion,
      repositoryRoot: root,
      planPath: join(parent, 'escape-plan.json'),
      desiredArtifacts: [generated('linked/escape.md', 'must remain outside the root\n')],
      createdAt: '2026-08-13T00:00:00.000Z',
    })).rejects.toThrow(/outside repository|symlink/i)
  })
})
