import { createHash } from 'node:crypto'
import { access, constants, cp, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { applyPlan } from '../../src/applier/apply-plan.js'
import { reconcileDrift } from '../../src/applier/reconcile.js'
import type { VirtualArtifact } from '../../src/domain/artifacts.js'
import { createChangePlan } from '../../src/planner/create-plan.js'
import { runCli, type CliIo } from '../../src/cli/main.js'

const owner = '@agent-policy/agent-policy-toolkit'
const toolkitVersion = '0.1.0-alpha.0'
const start = `<!-- agent-policy:start owner=${owner} -->`
const end = '<!-- agent-policy:end -->'
const fixture = fileURLToPath(new URL('../fixtures/repositories/drifted', import.meta.url))

function hash(content: string): string {
  return createHash('sha256').update(content, 'utf8').digest('hex')
}

function artifact(
  path: string,
  content: string,
  operation: VirtualArtifact['operation'] = 'replace',
): VirtualArtifact {
  return { path, content, sha256: hash(content), owner, operation }
}

function generated(body: string): string {
  return `<!--\nGenerated by ${owner}.\n-->\n${body}`
}

function realIo(): CliIo {
  return {
    stdout: '',
    stderr: '',
    confirm: async () => false,
    fs: {
      readFile: async (path) => readFile(path, 'utf8'),
      writeFile: async (path, contents) => writeFile(path, contents),
      exists: async (path) => access(path, constants.F_OK).then(() => true).catch(() => false),
    },
  }
}

async function copiedFixture(): Promise<{ readonly parent: string; readonly root: string }> {
  const parent = await mkdtemp(join(tmpdir(), 'agent-policy-removal-contract-'))
  const root = join(parent, 'consumer')
  await cp(fixture, root, { recursive: true })
  return { parent, root }
}

async function withWorkingDirectory<T>(root: string, action: () => Promise<T>): Promise<T> {
  const previous = process.cwd()
  process.chdir(root)
  try {
    return await action()
  } finally {
    process.chdir(previous)
  }
}

describe('removal and drift release contracts', () => {
  async function installCanonicalProjection(root: string, parent: string): Promise<void> {
    await withWorkingDirectory(root, async () => {
      const initPlan = join(parent, 'canonical-init-plan.json')
      await expect(runCli([
        'init',
        '--target', 'codex',
        '--bundles', 'core,typescript',
        '--plan', initPlan,
      ], realIo())).resolves.toBe(0)
      await expect(runCli(['apply', initPlan, '--yes'], realIo())).resolves.toBe(0)
    })
  }

  it('fails target removal on a drifted Managed Region before creating a plan', async () => {
    const { parent, root } = await copiedFixture()
    await installCanonicalProjection(root, parent)
    const path = 'AGENTS.md'
    const edited = (await readFile(join(root, path), 'utf8')).replace(
      '## Capability routing',
      '## Manually edited policy region',
    )
    await writeFile(join(root, path), edited)
    const planPath = join(parent, 'managed-region-drift-remove-plan.json')

    await withWorkingDirectory(root, async () => {
      const removal = realIo()
      await expect(runCli(['remove', '--target', 'codex', '--plan', planPath], removal)).resolves.toBe(1)
      expect(removal.stderr).toMatch(/drift|reconcile/i)
    })

    await expect(access(planPath)).rejects.toMatchObject({ code: 'ENOENT' })
    expect(await readFile(join(root, path), 'utf8')).toBe(edited)
    expect(await readFile(join(root, '.agents/skills/typescript/SKILL.md'), 'utf8')).toContain('TypeScript')
  })

  it('fails generated removal on a drifted generated skill before creating a plan', async () => {
    const { parent, root } = await copiedFixture()
    await installCanonicalProjection(root, parent)
    const path = '.agents/skills/typescript/SKILL.md'
    const edited = (await readFile(join(root, path), 'utf8')).replace(
      '# typescript policy',
      '# Manually edited TypeScript policy',
    )
    await writeFile(join(root, path), edited)
    const planPath = join(parent, 'generated-skill-drift-remove-plan.json')

    await withWorkingDirectory(root, async () => {
      const removal = realIo()
      await expect(runCli(['remove', '--generated', '--plan', planPath], removal)).resolves.toBe(1)
      expect(removal.stderr).toMatch(/drift|reconcile/i)
    })

    await expect(access(planPath)).rejects.toMatchObject({ code: 'ENOENT' })
    expect(await readFile(join(root, path), 'utf8')).toBe(edited)
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toContain('agent-policy:start')
  })

  it('plans a no-op target removal for an entirely unmanaged AGENTS.md', async () => {
    const { parent, root } = await copiedFixture()
    await writeFile(
      join(root, '.agent-policy/policy.yaml'),
      'schemaVersion: v1\ntoolkitVersion: 0.1.0-alpha.0\nbundles: []\ntargets: [codex]\n',
    )
    const unmanaged = '# Human-owned instructions\n'
    await writeFile(join(root, 'AGENTS.md'), unmanaged)
    const planPath = join(parent, 'unmanaged-target-remove-plan.json')

    await withWorkingDirectory(root, async () => {
      await expect(runCli(['remove', '--target', 'codex', '--plan', planPath], realIo())).resolves.toBe(0)
    })

    const plan = JSON.parse(await readFile(planPath, 'utf8')) as {
      readonly desiredArtifacts: readonly unknown[]
      readonly removals: readonly string[]
    }
    expect(plan.desiredArtifacts).toEqual([])
    expect(plan.removals).toEqual([])
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toBe(unmanaged)
  })

  it('removes owned projections after canonical sources are removed', async () => {
    const { parent, root } = await copiedFixture()
    await installCanonicalProjection(root, parent)
    await rm(join(root, '.agent-policy/policy.yaml'))
    const planPath = join(parent, 'source-less-generated-remove-plan.json')

    await withWorkingDirectory(root, async () => {
      await expect(runCli(['remove', '--generated', '--plan', planPath], realIo())).resolves.toBe(0)
      await expect(runCli(['apply', planPath, '--yes'], realIo())).resolves.toBe(0)
    })

    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toContain('# Keep this hand-written footer')
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).not.toContain(start)
    await expect(access(join(root, '.agents/skills/typescript/SKILL.md'))).rejects.toMatchObject({ code: 'ENOENT' })
  })

  it('refuses source-less generated removal when owned output is drifted', async () => {
    const { parent, root } = await copiedFixture()
    await installCanonicalProjection(root, parent)
    const skillPath = join(root, '.agents/skills/typescript/SKILL.md')
    await writeFile(skillPath, `${await readFile(skillPath, 'utf8')}\nManual drift\n`)
    await rm(join(root, '.agent-policy/policy.yaml'))
    const planPath = join(parent, 'source-less-drift-remove-plan.json')

    await withWorkingDirectory(root, async () => {
      const removal = realIo()
      await expect(runCli(['remove', '--generated', '--plan', planPath], removal)).resolves.toBe(1)
      expect(removal.stderr).toMatch(/drift|reconcile/i)
    })

    await expect(access(planPath)).rejects.toMatchObject({ code: 'ENOENT' })
    expect(await readFile(skillPath, 'utf8')).toContain('Manual drift')
  })

  it('rejects generated-copy hash divergence without overwriting the manual copy', async () => {
    const { parent, root } = await copiedFixture()
    const path = '.agents/skills/typescript/SKILL.md'
    const desired = generated('# Reviewed TypeScript policy\n')
    const reviewed = await createChangePlan({
      command: 'update',
      toolkitVersion,
      repositoryRoot: root,
      planPath: join(parent, 'generated-drift-plan.json'),
      sourcePaths: ['.agent-policy/policy.yaml'],
      desiredArtifacts: [artifact(path, desired)],
      createdAt: '2026-08-13T00:00:00.000Z',
    })
    const edited = generated('# Manual TypeScript edit\n')
    await writeFile(join(root, path), edited)

    await expect(applyPlan(reviewed, { repositoryRoot: root, toolkitVersion })).resolves.toMatchObject({
      ok: false,
      code: 'artifact-drift',
      paths: [path],
    })
    expect(await readFile(join(root, path), 'utf8')).toBe(edited)
  })

  it('rejects a manual Managed Region edit before changing its surrounding bytes', async () => {
    const { parent, root } = await copiedFixture()
    const path = 'AGENTS.md'
    const current = await readFile(join(root, path), 'utf8')
    const desired = current.replace('Old generated policy body.', 'Reviewed generated policy body.')
    const reviewed = await createChangePlan({
      command: 'update',
      toolkitVersion,
      repositoryRoot: root,
      planPath: join(parent, 'managed-region-drift-plan.json'),
      desiredArtifacts: [artifact(path, desired, 'managed-region')],
      createdAt: '2026-08-13T00:00:00.000Z',
    })
    const edited = current.replace('Old generated policy body.', 'Manual region edit.')
    await writeFile(join(root, path), edited)

    await expect(applyPlan(reviewed, { repositoryRoot: root, toolkitVersion })).resolves.toMatchObject({
      ok: false,
      code: 'artifact-drift',
      paths: [path],
    })
    expect(await readFile(join(root, path), 'utf8')).toBe(edited)
  })

  it('does not recreate a missing generated file after review', async () => {
    const { parent, root } = await copiedFixture()
    const path = '.agents/skills/typescript/SKILL.md'
    const reviewed = await createChangePlan({
      command: 'update',
      toolkitVersion,
      repositoryRoot: root,
      planPath: join(parent, 'missing-generated-plan.json'),
      sourcePaths: ['.agent-policy/policy.yaml'],
      desiredArtifacts: [artifact(path, generated('# Reviewed policy\n'))],
      createdAt: '2026-08-13T00:00:00.000Z',
    })
    await rm(join(root, path))

    await expect(applyPlan(reviewed, { repositoryRoot: root, toolkitVersion })).resolves.toMatchObject({
      ok: false,
      code: 'artifact-drift',
      paths: [path],
    })
    await expect(access(join(root, path))).rejects.toMatchObject({ code: 'ENOENT' })
  })

  it.each([
    ['target', ['remove', '--target', 'codex']],
    ['generated', ['remove', '--generated']],
  ] as const)('uninstalls the %s projection while preserving policy sources and unrelated target output', async (_mode, command) => {
    const { parent, root } = await copiedFixture()
    await installCanonicalProjection(root, parent)
    const policyBefore = await readFile(join(root, '.agent-policy/policy.yaml'), 'utf8')
    const packageBefore = await readFile(join(root, 'package.json'), 'utf8')
    const foreignPath = join(root, '.agents/skills/foreign/SKILL.md')
    const foreignBefore = await readFile(foreignPath, 'utf8')
    const planPath = join(parent, `${command[1] === '--generated' ? 'generated' : 'target'}-remove-plan.json`)

    await withWorkingDirectory(root, async () => {
      const removal = realIo()
      await expect(runCli([...command, '--plan', planPath], removal)).resolves.toBe(0)
      await expect(runCli(['apply', planPath, '--yes'], realIo())).resolves.toBe(0)
    })

    expect(await readFile(join(root, '.agent-policy/policy.yaml'), 'utf8')).toBe(policyBefore)
    expect(await readFile(join(root, 'package.json'), 'utf8')).toBe(packageBefore)
    expect(await readFile(foreignPath, 'utf8')).toBe(foreignBefore)
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toContain('# Keep this hand-written footer')
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).not.toContain(start)
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).not.toContain(end)
    await expect(access(join(root, '.agents/skills/typescript/SKILL.md'))).rejects.toMatchObject({ code: 'ENOENT' })
  })

  it('reinitializes to byte-identical artifacts after removing a target from preserved sources', async () => {
    const { parent, root } = await copiedFixture()
    const initialAgents = '# Existing root instructions\n'
    await writeFile(join(root, 'AGENTS.md'), initialAgents)
    const firstPlanPath = join(parent, 'first-init-plan.json')
    const removePlanPath = join(parent, 'reinit-remove-plan.json')
    const secondPlanPath = join(parent, 'second-init-plan.json')

    await withWorkingDirectory(root, async () => {
      await expect(runCli([
        'init',
        '--target', 'codex',
        '--bundles', 'core,typescript',
        '--plan', firstPlanPath,
      ], realIo())).resolves.toBe(0)
      await expect(runCli(['apply', firstPlanPath, '--yes'], realIo())).resolves.toBe(0)
    })
    const artifactPaths = ['AGENTS.md', '.agents/skills/typescript/SKILL.md']
    const firstArtifacts = new Map(
      await Promise.all(artifactPaths.map(async (path) => [path, await readFile(join(root, path), 'utf8')] as const)),
    )

    await withWorkingDirectory(root, async () => {
      await expect(runCli([
        'remove',
        '--target', 'codex',
        '--plan', removePlanPath,
      ], realIo())).resolves.toBe(0)
      await expect(runCli(['apply', removePlanPath, '--yes'], realIo())).resolves.toBe(0)
    })
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toBe(initialAgents)
    expect(await readFile(join(root, '.agent-policy/policy.yaml'), 'utf8')).toContain('bundles: [typescript]')

    await withWorkingDirectory(root, async () => {
      await expect(runCli([
        'init',
        '--target', 'codex',
        '--bundles', 'core,typescript',
        '--plan', secondPlanPath,
      ], realIo())).resolves.toBe(0)
      await expect(runCli(['apply', secondPlanPath, '--yes'], realIo())).resolves.toBe(0)
    })
    for (const path of artifactPaths) {
      const actual = await readFile(join(root, path), 'utf8')
      const expected = firstArtifacts.get(path)
      expect(expected).toBeDefined()
      expect(actual).toBe(expected)
      expect(hash(actual)).toBe(hash(expected ?? ''))
    }
  })

  it('leaves non-interactive drift unresolved without choosing adoption or regeneration', () => {
    const proposal = reconcileDrift(undefined, {
      artifactPath: 'AGENTS.md',
      currentContent: 'manual edit\n',
    })

    expect(proposal).toMatchObject({
      kind: 'unresolved',
      reason: 'non-interactive-drift',
    })
    expect(proposal).not.toHaveProperty('choice')
    expect(proposal).not.toHaveProperty('canonicalSourceChanges')
    expect(proposal).not.toHaveProperty('discardArtifactEdits')
  })
})
