import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { describe, expect, it } from 'vitest'

import { codexAdapter } from '../../src/adapters/codex/project.js'
import { loadCatalog, loadWorkflowSkills } from '../../src/catalog/load-catalog.js'
import { loadBundles } from '../../src/catalog/load-bundles.js'
import { compileCodex } from '../../src/cli/commands/common.js'
import { resolvePolicy } from '../../src/compiler/resolve-policy.js'
import { hasValidPolicyLockHash, POLICY_LOCK_PATH } from '../../src/planner/policy-lock.js'
import { ARTIFACT_HASH_PLACEHOLDER } from '../../src/planner/hash.js'

const toolkitRoot = fileURLToPath(new URL('../..', import.meta.url))
const toolkitVersion = '0.1.0-alpha.3'

describe('canonical workflow skill projection contract', () => {
  it('discovers and loads canonical workflow skills from skills/*/SKILL.md', async () => {
    const skills = await loadWorkflowSkills(toolkitRoot)
    const catalog = await loadCatalog(toolkitRoot)

    expect(skills.length).toBeGreaterThan(0)
    expect(catalog.workflowSkills).toEqual(skills)

    const maintainer = skills.find((s) => s.name === 'policy-maintainer')
    expect(maintainer).toBeDefined()
    expect(maintainer?.name).toBe('policy-maintainer')
    expect(maintainer?.description).toContain('Explicit invocation only')
    expect(maintainer?.path).toBe('skills/policy-maintainer/SKILL.md')
    expect(maintainer?.body).toContain('# policy-maintainer')
    expect(maintainer?.body).toContain('## Mission')
    expect(maintainer?.body).toContain('## Enforcement-First Classification Rubric')
    expect(maintainer?.body).toContain('classify-existing')
  })

  it('projects skills/policy-maintainer/SKILL.md into .agents/skills/policy-maintainer/SKILL.md via codexAdapter', async () => {
    const skills = await loadWorkflowSkills(toolkitRoot)
    const maintainer = skills.find((s) => s.name === 'policy-maintainer')
    expect(maintainer).toBeDefined()

    const bundles = await loadBundles(toolkitRoot)
    const catalog = await loadCatalog(toolkitRoot)
    const resolvedPolicy = resolvePolicy(
      { rules: catalog.rules, bundles },
      {
        schemaVersion: 'v1',
        toolkitVersion,
        bundles: ['typescript'],
        targets: ['codex'],
      },
    )

    const artifacts = await codexAdapter.project({
      toolkitVersion,
      canonicalSourceHash: '0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef',
      resolvedPolicy,
      bundles,
      workflowSkills: [maintainer!],
    })

    const projectedSkill = artifacts.find((a) => a.path === '.agents/skills/policy-maintainer/SKILL.md')
    expect(projectedSkill).toBeDefined()
    expect(projectedSkill?.operation).toBe('replace')
    expect(projectedSkill?.owner).toBe('@agent-policy/agent-policy-toolkit')

    const content = projectedSkill?.content ?? ''
    expect(content).toMatch(/^---\nname: policy-maintainer\n/)
    expect(content).toContain('Generated by @agent-policy/agent-policy-toolkit')
    expect(content).toContain('Toolkit version: 0.1.0-alpha.3')
    expect(content).toContain('Adapter knowledge version: codex-2026-08-12')
    expect(content).toContain('Canonical source hash: 0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef')
    expect(content).toContain('Artifact hash:')
    expect(content).not.toContain(ARTIFACT_HASH_PLACEHOLDER)
    expect(content).toContain('# policy-maintainer')
    expect(content).toContain('## Mission')
    expect(content).toContain('classify-existing')

    // Verify artifact sha256 matches actual content
    expect(projectedSkill?.sha256).toBeDefined()
    expect(projectedSkill?.sha256).toMatch(/^[0-9a-f]{64}$/)
  })

  it('includes projected workflow skill in compilation artifacts and policy.lock.json', async () => {
    const parent = await mkdtemp(join(tmpdir(), 'agent-policy-workflow-projection-'))
    const repoRoot = join(parent, 'repo')
    await mkdir(join(repoRoot, '.agent-policy'), { recursive: true })

    const manifest = [
      'schemaVersion: v1',
      `toolkitVersion: ${toolkitVersion}`,
      'bundles: [typescript]',
      'targets: [codex]',
      '',
    ].join('\n')
    await writeFile(join(repoRoot, '.agent-policy/policy.yaml'), manifest)

    const compilation = await compileCodex({
      repositoryRoot: repoRoot,
      toolkitRoot,
      toolkitVersion,
    })

    const skillArtifact = compilation.artifacts.find((a) => a.path === '.agents/skills/policy-maintainer/SKILL.md')
    expect(skillArtifact).toBeDefined()

    const lockArtifact = compilation.artifacts.find((a) => a.path === POLICY_LOCK_PATH)
    expect(lockArtifact).toBeDefined()
    expect(hasValidPolicyLockHash(lockArtifact!.content)).toBe(true)

    const lockJson = JSON.parse(lockArtifact!.content) as {
      managedArtifactHashes: Record<string, { sha256: string; operation: string; owner: string }>
    }
    expect(lockJson.managedArtifactHashes['.agents/skills/policy-maintainer/SKILL.md']).toEqual({
      sha256: skillArtifact!.sha256,
      operation: 'replace',
      owner: '@agent-policy/agent-policy-toolkit',
    })
  })
})
