import { createHash } from 'node:crypto'
import {
  lstat,
  mkdir,
  mkdtemp,
  open,
  readFile,
  readdir,
  symlink,
  writeFile,
} from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { applyPlan } from '../../src/applier/apply-plan.js'
import { reconcileDrift } from '../../src/applier/reconcile.js'
import type { TransactionHooks } from '../../src/applier/transaction.js'
import type { VirtualArtifact } from '../../src/domain/artifacts.js'
import type { ChangePlan } from '../../src/domain/change-plan.js'
import { createChangePlan } from '../../src/planner/create-plan.js'
import { computePlanHash } from '../../src/planner/serialize-plan.js'

const owner = '@agent-policy/agent-policy-toolkit'
const toolkitVersion = '0.1.0-alpha.0'
const start = `<!-- agent-policy:start owner=${owner} -->`
const end = '<!-- agent-policy:end -->'

function hash(content: string): string {
  return createHash('sha256').update(content, 'utf8').digest('hex')
}

function generated(content: string): string {
  return `<!--\nGenerated by ${owner}.\n-->\n${content}`
}

function artifact(
  path: string,
  content: string,
  operation: VirtualArtifact['operation'] = 'replace',
): VirtualArtifact {
  return { path, content, sha256: hash(content), owner, operation }
}

async function sandbox(): Promise<{ readonly parent: string; readonly root: string }> {
  const parent = await mkdtemp(join(tmpdir(), 'agent-policy-apply-test-'))
  const root = join(parent, 'consumer')
  await mkdir(join(root, '.agent-policy'), { recursive: true })
  await writeFile(join(root, '.agent-policy/policy.yaml'), 'schemaVersion: v1\n')
  return { parent, root }
}

async function plan(
  parent: string,
  root: string,
  desiredArtifacts: readonly VirtualArtifact[],
  removals: readonly string[] = [],
): Promise<ChangePlan> {
  return createChangePlan({
    command: 'update',
    toolkitVersion,
    repositoryRoot: root,
    planPath: join(parent, 'reviewed-plan.json'),
    sourcePaths: ['.agent-policy/policy.yaml'],
    desiredArtifacts,
    removals,
    createdAt: '2026-08-12T00:00:00.000Z',
  })
}

async function expectMissing(path: string): Promise<void> {
  await expect(lstat(path)).rejects.toMatchObject({ code: 'ENOENT' })
}

async function expectNoTransactionDebris(directory: string): Promise<void> {
  const names = await readdir(directory)
  expect(names.filter((name) => name.includes('.agent-policy-transaction-'))).toEqual([])
}

function rehashPlan(planToChange: ChangePlan, changes: Partial<ChangePlan>): ChangePlan {
  const changed = { ...planToChange, ...changes }
  return { ...changed, planHash: computePlanHash(changed) }
}

describe('transactional plan application', () => {
  it('applies create, replace, Managed Region, and removal work as one transaction', async () => {
    const { parent, root } = await sandbox()
    const previousGenerated = generated('old\n')
    const previousRemoved = generated('remove me\n')
    const previousAgents = `# Team-owned text\n\n${start}\nold policy\n${end}\n`
    const nextAgents = `# Team-owned text\n\n${start}\nnew policy\n${end}\n`
    await mkdir(join(root, '.agents/skills/testing'), { recursive: true })
    await mkdir(join(root, '.agents/skills/old'), { recursive: true })
    await writeFile(join(root, '.agents/skills/testing/SKILL.md'), previousGenerated)
    await writeFile(join(root, '.agents/skills/old/SKILL.md'), previousRemoved)
    await writeFile(join(root, 'AGENTS.md'), previousAgents)
    const reviewed = await plan(parent, root, [
      artifact('.agents/skills/react/SKILL.md', generated('react\n')),
      artifact('.agents/skills/testing/SKILL.md', generated('new\n')),
      artifact('AGENTS.md', nextAgents, 'managed-region'),
    ], ['.agents/skills/old/SKILL.md'])

    const result = await applyPlan(reviewed, { repositoryRoot: root, toolkitVersion })

    expect(result).toEqual({
      ok: true,
      appliedPaths: [
        '.agents/skills/react/SKILL.md',
        '.agents/skills/testing/SKILL.md',
        'AGENTS.md',
        '.agents/skills/old/SKILL.md',
      ],
    })
    expect(await readFile(join(root, '.agents/skills/react/SKILL.md'), 'utf8')).toBe(
      generated('react\n'),
    )
    expect(await readFile(join(root, '.agents/skills/testing/SKILL.md'), 'utf8')).toBe(
      generated('new\n'),
    )
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toBe(nextAgents)
    await expectMissing(join(root, '.agents/skills/old/SKILL.md'))
    await expectNoTransactionDebris(root)
    await expectNoTransactionDebris(join(root, '.agents/skills/testing'))
  })

  it('preserves an original backup changed through an open descriptor before cleanup', async () => {
    const { parent, root } = await sandbox()
    const previous = generated('old\n')
    const desired = generated('reviewed\n')
    await writeFile(join(root, 'owned.md'), previous)
    const reviewed = await plan(parent, root, [artifact('owned.md', desired)])
    let originalHandle: Awaited<ReturnType<typeof open>> | undefined
    const hooks: TransactionHooks = {
      beforeRename: async ({ phase }) => {
        if (phase === 'backup') {
          originalHandle = await open(join(root, 'owned.md'), 'r+')
        }
        if (phase === 'install' && originalHandle !== undefined) {
          await originalHandle.truncate(0)
          await originalHandle.writeFile(generated('open descriptor edit\n'), 'utf8')
          await originalHandle.sync()
        }
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })
    await originalHandle?.close()

    expect(result).toMatchObject({ ok: true })
    if (!result.ok) throw new Error('expected successful application with cleanup warning')
    expect(result.warnings).toEqual([
      expect.stringMatching(/BACKUP CLEANUP FAILED.*owned\.md.*preserved/i),
    ])
    expect(await readFile(join(root, 'owned.md'), 'utf8')).toBe(desired)
    const backup = (await readdir(root)).find((name) => name.endsWith('.backup'))
    if (backup === undefined) throw new Error('expected preserved backup')
    expect(await readFile(join(root, backup), 'utf8')).toBe(generated('open descriptor edit\n'))
  })

  it('adds a reviewed owned region to an unchanged unmanaged entry file', async () => {
    const { parent, root } = await sandbox()
    const previous = '# Team-owned text\n'
    const desired = `# Team-owned text\n\n${start}\npolicy\n${end}\n`
    await writeFile(join(root, 'AGENTS.md'), previous)
    const reviewed = await plan(parent, root, [artifact('AGENTS.md', desired, 'managed-region')])

    const result = await applyPlan(reviewed, { repositoryRoot: root, toolkitVersion })

    expect(result).toMatchObject({ ok: true })
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toBe(desired)
  })

  it('rejects a stale canonical source hash before writing any target', async () => {
    const { parent, root } = await sandbox()
    const reviewed = await plan(parent, root, [artifact('new.md', generated('new\n'))])
    await writeFile(join(root, '.agent-policy/policy.yaml'), 'schemaVersion: changed\n')

    const result = await applyPlan(reviewed, { repositoryRoot: root, toolkitVersion })

    expect(result).toMatchObject({ ok: false, code: 'source-drift' })
    await expectMissing(join(root, 'new.md'))
  })

  it('revalidates every precondition again after preparing sibling temporaries', async () => {
    const { parent, root } = await sandbox()
    const reviewed = await plan(parent, root, [artifact('new.md', generated('new\n'))])
    const hooks: TransactionHooks = {
      beforePrepare: async () => {
        await writeFile(join(root, '.agent-policy/policy.yaml'), 'changed during preparation\n')
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })

    expect(result).toMatchObject({ ok: false, code: 'transaction-failed' })
    await expectMissing(join(root, 'new.md'))
    await expectNoTransactionDebris(root)
  })

  it('revalidates canonical sources in the final path-check-to-write window', async () => {
    const { parent, root } = await sandbox()
    const reviewed = await plan(parent, root, [artifact('new.md', generated('new\n'))])
    const hooks: TransactionHooks = {
      afterPathCheck: async ({ phase }) => {
        if (phase === 'prepare') {
          await writeFile(join(root, '.agent-policy/policy.yaml'), 'changed at write boundary\n')
        }
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })

    expect(result).toMatchObject({ ok: false, code: 'transaction-failed' })
    await expectMissing(join(root, 'new.md'))
    await expectNoTransactionDebris(root)
  })

  it('rejects a changed generated artifact before writing another target', async () => {
    const { parent, root } = await sandbox()
    const previous = generated('old\n')
    await writeFile(join(root, 'owned.md'), previous)
    const reviewed = await plan(parent, root, [
      artifact('owned.md', generated('new\n')),
      artifact('second.md', generated('second\n')),
    ])
    await writeFile(join(root, 'owned.md'), generated('edited after review\n'))

    const result = await applyPlan(reviewed, { repositoryRoot: root, toolkitVersion })

    expect(result).toMatchObject({ ok: false, code: 'artifact-drift' })
    expect(await readFile(join(root, 'owned.md'), 'utf8')).toBe(generated('edited after review\n'))
    await expectMissing(join(root, 'second.md'))
  })

  it('rejects changed unmanaged text even when an owned Managed Region is unchanged', async () => {
    const { parent, root } = await sandbox()
    const previous = `# Team text\n\n${start}\nold policy\n${end}\n`
    const desired = `# Team text\n\n${start}\nnew policy\n${end}\n`
    await writeFile(join(root, 'AGENTS.md'), previous)
    const reviewed = await plan(parent, root, [artifact('AGENTS.md', desired, 'managed-region')])
    const concurrent = `# Concurrent team edit\n\n${start}\nold policy\n${end}\n`
    await writeFile(join(root, 'AGENTS.md'), concurrent)

    const result = await applyPlan(reviewed, { repositoryRoot: root, toolkitVersion })

    expect(result).toMatchObject({ ok: false, code: 'artifact-drift' })
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toBe(concurrent)
  })

  it('restores originals and removes new targets after an interrupted mid-transaction write', async () => {
    const { parent, root } = await sandbox()
    const previous = generated('old\n')
    await writeFile(join(root, 'a-owned.md'), previous)
    const reviewed = await plan(parent, root, [
      artifact('a-owned.md', generated('new\n')),
      artifact('nested/b-new.md', generated('created\n')),
    ])
    const hooks: TransactionHooks = {
      beforeRename: ({ phase, operationIndex }) => {
        if (phase === 'install' && operationIndex === 1) throw new Error('simulated interruption')
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })

    expect(result).toMatchObject({
      ok: false,
      code: 'transaction-failed',
      rollbackFailures: [],
    })
    expect(await readFile(join(root, 'a-owned.md'), 'utf8')).toBe(previous)
    await expectMissing(join(root, 'nested/b-new.md'))
    await expectMissing(join(root, 'nested'))
    await expectNoTransactionDebris(root)
  })

  it('preserves a concurrently edited installed target and its original backup on rollback', async () => {
    const { parent, root } = await sandbox()
    await writeFile(join(root, 'a-owned.md'), generated('old\n'))
    const reviewed = await plan(parent, root, [
      artifact('a-owned.md', generated('reviewed\n')),
      artifact('b-new.md', generated('created\n')),
    ])
    let installedHandle: Awaited<ReturnType<typeof open>> | undefined
    const hooks: TransactionHooks = {
      beforeRename: async ({ phase, operationIndex }) => {
        if (phase === 'install' && operationIndex === 1) {
          installedHandle = await open(join(root, 'a-owned.md'), 'r+')
          await installedHandle.truncate(0)
          await installedHandle.writeFile(generated('concurrent\n'), 'utf8')
          await installedHandle.sync()
          throw new Error('stop after concurrent edit')
        }
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })
    await installedHandle?.close()

    expect(result).toMatchObject({ ok: false, code: 'transaction-failed' })
    if (result.ok) throw new Error('expected transaction failure')
    expect(result.message).toMatch(/ROLLBACK FAILED/i)
    expect(result.rollbackFailures).toEqual([
      expect.stringMatching(/a-owned\.md.*changed during rollback/i),
      expect.stringMatching(/a-owned\.md.*backup.*preserved/i),
    ])
    expect(await readFile(join(root, 'a-owned.md'), 'utf8')).toBe(generated('concurrent\n'))
    expect((await readdir(root)).some((name) => name.includes('.backup'))).toBe(true)
  })

  it('uses installed inode identity when concurrent replacement has identical bytes', async () => {
    const { parent, root } = await sandbox()
    await writeFile(join(root, 'a-owned.md'), generated('old\n'))
    const reviewedContent = generated('reviewed\n')
    const reviewed = await plan(parent, root, [
      artifact('a-owned.md', reviewedContent),
      artifact('b-new.md', generated('created\n')),
    ])
    const hooks: TransactionHooks = {
      beforeRename: async ({ phase, operationIndex }) => {
        if (phase !== 'install' || operationIndex !== 1) return
        const concurrentPath = join(root, 'concurrent.md')
        await writeFile(concurrentPath, reviewedContent)
        const { rename } = await import('node:fs/promises')
        await rename(concurrentPath, join(root, 'a-owned.md'))
        throw new Error('stop after same-byte replacement')
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })

    expect(result).toMatchObject({ ok: false, code: 'transaction-failed' })
    if (result.ok) throw new Error('expected transaction failure')
    expect(result.rollbackFailures).toEqual([
      expect.stringMatching(/a-owned\.md.*changed during rollback/i),
      expect.stringMatching(/a-owned\.md.*backup.*preserved/i),
    ])
    expect(await readFile(join(root, 'a-owned.md'), 'utf8')).toBe(reviewedContent)
    expect((await readdir(root)).some((name) => name.includes('.backup'))).toBe(true)
  })

  it('removes shared created parent directories deepest-first after rollback', async () => {
    const { parent, root } = await sandbox()
    const reviewed = await plan(parent, root, [
      artifact('nested/a/first.md', generated('first\n')),
      artifact('nested/b/second.md', generated('second\n')),
    ])
    const hooks: TransactionHooks = {
      beforeRename: ({ phase, operationIndex }) => {
        if (phase === 'install' && operationIndex === 1) throw new Error('stop in sibling')
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })

    expect(result).toMatchObject({
      ok: false,
      code: 'transaction-failed',
      rollbackFailures: [],
    })
    await expectMissing(join(root, 'nested'))
  })

  it('does not overwrite a target created at the mutation boundary', async () => {
    const { parent, root } = await sandbox()
    const reviewed = await plan(parent, root, [artifact('new.md', generated('reviewed\n'))])
    const hooks: TransactionHooks = {
      beforeRename: async ({ phase }) => {
        if (phase === 'install') await writeFile(join(root, 'new.md'), 'concurrent user data\n')
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })

    expect(result).toMatchObject({ ok: false, code: 'transaction-failed' })
    expect(await readFile(join(root, 'new.md'), 'utf8')).toBe('concurrent user data\n')
  })

  it('restores an existing target edited at the mutation boundary', async () => {
    const { parent, root } = await sandbox()
    await writeFile(join(root, 'owned.md'), generated('old\n'))
    const reviewed = await plan(parent, root, [artifact('owned.md', generated('reviewed\n'))])
    const hooks: TransactionHooks = {
      beforeRename: async ({ phase }) => {
        if (phase === 'backup') await writeFile(join(root, 'owned.md'), generated('concurrent\n'))
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })

    expect(result).toMatchObject({ ok: false, code: 'transaction-failed' })
    expect(await readFile(join(root, 'owned.md'), 'utf8')).toBe(generated('concurrent\n'))
  })

  it('rejects a plan whose canonical hash is invalid', async () => {
    const { parent, root } = await sandbox()
    const reviewed = await plan(parent, root, [artifact('new.md', generated('new\n'))])
    const damaged = { ...reviewed, command: 'tampered' }

    const result = await applyPlan(damaged, { repositoryRoot: root, toolkitVersion })

    expect(result).toMatchObject({ ok: false, code: 'invalid-plan' })
    await expectMissing(join(root, 'new.md'))
  })

  it('rejects repository-root and toolkit-version mismatches', async () => {
    const first = await sandbox()
    const second = await sandbox()
    const reviewed = await plan(first.parent, first.root, [artifact('new.md', generated('new\n'))])

    const rootResult = await applyPlan(reviewed, {
      repositoryRoot: second.root,
      toolkitVersion,
    })
    const versionResult = await applyPlan(reviewed, {
      repositoryRoot: first.root,
      toolkitVersion: '9.9.9',
    })

    expect(rootResult).toMatchObject({ ok: false, code: 'repository-mismatch' })
    expect(versionResult).toMatchObject({ ok: false, code: 'toolkit-mismatch' })
    await expectMissing(join(first.root, 'new.md'))
    await expectMissing(join(second.root, 'new.md'))
  })

  it('revalidates Managed Region hashes and ownership even for a consistently rehashed plan', async () => {
    const { parent, root } = await sandbox()
    const previous = `# Team\n\n${start}\nold\n${end}\n`
    const desired = `# Team\n\n${start}\nnew\n${end}\n`
    await writeFile(join(root, 'AGENTS.md'), previous)
    const reviewed = await plan(parent, root, [artifact('AGENTS.md', desired, 'managed-region')])
    const damagedRegionPlan = rehashPlan(reviewed, {
      currentManagedRegionHashes: { 'AGENTS.md': hash(`${start}\nforged\n${end}`) },
    })

    const regionResult = await applyPlan(damagedRegionPlan, { repositoryRoot: root, toolkitVersion })
    expect(regionResult).toMatchObject({ ok: false, code: 'artifact-drift' })
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toBe(previous)

    const foreign = previous.replace(owner, '@foreign/tool')
    await writeFile(join(root, 'AGENTS.md'), foreign)
    const foreignPlan = rehashPlan(reviewed, {
      currentArtifactHashes: { 'AGENTS.md': hash(foreign) },
      currentManagedRegionHashes: {},
    })
    const ownershipResult = await applyPlan(foreignPlan, { repositoryRoot: root, toolkitVersion })
    expect(ownershipResult).toMatchObject({ ok: false, code: 'ownership-drift' })
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toBe(foreign)
  })

  it('rejects a rehashed plan that would drop generated ownership', async () => {
    const { parent, root } = await sandbox()
    const previous = generated('old\n')
    await writeFile(join(root, 'owned.md'), previous)
    const reviewed = await plan(parent, root, [artifact('owned.md', generated('new\n'))])
    const unowned = artifact('owned.md', 'hand-written replacement\n')
    const damaged = rehashPlan(reviewed, { desiredArtifacts: [unowned] })

    const result = await applyPlan(damaged, { repositoryRoot: root, toolkitVersion })

    expect(result).toMatchObject({ ok: false, code: 'invalid-plan' })
    expect(await readFile(join(root, 'owned.md'), 'utf8')).toBe(previous)
  })

  it('refuses to remove an unmanaged file even when its reviewed full hash still matches', async () => {
    const { parent, root } = await sandbox()
    await writeFile(join(root, 'notes.md'), 'team-owned notes\n')
    const reviewed = await plan(parent, root, [], ['notes.md'])

    const result = await applyPlan(reviewed, { repositoryRoot: root, toolkitVersion })

    expect(result).toMatchObject({ ok: false, code: 'ownership-drift' })
    expect(await readFile(join(root, 'notes.md'), 'utf8')).toBe('team-owned notes\n')
  })

  it('revalidates target confinement after planning and does not write through a new symlink', async () => {
    const { parent, root } = await sandbox()
    const outside = join(parent, 'outside')
    await mkdir(join(root, 'safe'))
    await mkdir(outside)
    const reviewed = await plan(parent, root, [artifact('safe/new.md', generated('new\n'))])
    await import('node:fs/promises').then(({ rm }) => rm(join(root, 'safe'), { recursive: true }))
    await symlink(outside, join(root, 'safe'))

    const result = await applyPlan(reviewed, { repositoryRoot: root, toolkitVersion })

    expect(result).toMatchObject({ ok: false, code: 'unsafe-target' })
    await expectMissing(join(outside, 'new.md'))
  })

  it('applies safely beneath a confined in-repository symlink ancestor', async () => {
    const { parent, root } = await sandbox()
    await mkdir(join(root, 'actual/sub'), { recursive: true })
    await symlink(join(root, 'actual'), join(root, 'linked'))
    const reviewed = await plan(parent, root, [
      artifact('linked/sub/new.md', generated('new\n')),
    ])

    const result = await applyPlan(reviewed, { repositoryRoot: root, toolkitVersion })

    expect(result).toMatchObject({ ok: true })
    expect(await readFile(join(root, 'actual/sub/new.md'), 'utf8')).toBe(generated('new\n'))
  })

  it('rolls back safely beneath a confined in-repository symlink ancestor', async () => {
    const { parent, root } = await sandbox()
    await mkdir(join(root, 'actual/sub'), { recursive: true })
    await symlink(join(root, 'actual'), join(root, 'linked'))
    await writeFile(join(root, 'actual/sub/owned.md'), generated('old\n'))
    const reviewed = await plan(parent, root, [
      artifact('linked/sub/owned.md', generated('new\n')),
      artifact('linked/sub/second.md', generated('second\n')),
    ])
    const hooks: TransactionHooks = {
      beforeRename: ({ phase, operationIndex }) => {
        if (phase === 'install' && operationIndex === 1) throw new Error('stop under symlink')
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })

    expect(result).toMatchObject({
      ok: false,
      code: 'transaction-failed',
      rollbackFailures: [],
    })
    expect(await readFile(join(root, 'actual/sub/owned.md'), 'utf8')).toBe(generated('old\n'))
    await expectMissing(join(root, 'actual/sub/second.md'))
    await expectNoTransactionDebris(join(root, 'actual/sub'))
  })

  it('revalidates confinement immediately before preparing a sibling temporary', async () => {
    const { parent, root } = await sandbox()
    const outside = join(parent, 'outside')
    const movedSafe = join(parent, 'moved-safe')
    await mkdir(join(root, 'safe'))
    await mkdir(outside)
    const reviewed = await plan(parent, root, [artifact('safe/new.md', generated('new\n'))])
    const hooks: TransactionHooks = {
      afterPathCheck: async ({ phase }) => {
        if (phase !== 'prepare') return
        const { rename } = await import('node:fs/promises')
        await rename(join(root, 'safe'), movedSafe)
        await symlink(outside, join(root, 'safe'))
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })

    expect(result).toMatchObject({ ok: false, code: 'transaction-failed' })
    expect(await readdir(outside)).toEqual([])
  })

  it('revalidates confinement at the mutation boundary after a parent symlink swap', async () => {
    const { parent, root } = await sandbox()
    const outside = join(parent, 'outside')
    const movedSafe = join(parent, 'moved-safe')
    await mkdir(join(root, 'safe'))
    await mkdir(outside)
    await writeFile(join(root, 'safe/owned.md'), generated('old\n'))
    const reviewed = await plan(parent, root, [
      artifact('safe/owned.md', generated('reviewed\n')),
    ])
    let outsideTrapPath = ''
    const hooks: TransactionHooks = {
      afterPathCheck: async ({ phase }) => {
        if (phase !== 'backup') return
        const preparedName = (await readdir(join(root, 'safe')))
          .find((name) => name.includes('.agent-policy-transaction-'))
        if (preparedName === undefined) throw new Error('expected prepared sibling')
        const { rename } = await import('node:fs/promises')
        await rename(join(root, 'safe'), movedSafe)
        await symlink(outside, join(root, 'safe'))
        outsideTrapPath = join(outside, preparedName)
        await writeFile(outsideTrapPath, 'outside trap\n')
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })

    expect(result).toMatchObject({ ok: false, code: 'transaction-failed' })
    await expectMissing(join(outside, 'owned.md'))
    expect(await readFile(outsideTrapPath, 'utf8')).toBe('outside trap\n')
    expect(await readFile(join(movedSafe, 'owned.md'), 'utf8')).toBe(generated('old\n'))
  })

  it('anchors no-replace installation to the reviewed parent directory', async () => {
    const { parent, root } = await sandbox()
    const outside = join(parent, 'outside')
    const movedSafe = join(parent, 'moved-safe')
    await mkdir(join(root, 'safe'))
    await mkdir(outside)
    const reviewed = await plan(parent, root, [artifact('safe/new.md', generated('new\n'))])
    let outsideTrapPath = ''
    const hooks: TransactionHooks = {
      afterPathCheck: async ({ phase }) => {
        if (phase !== 'install') return
        const preparedName = (await readdir(join(root, 'safe')))
          .find((name) => name.includes('.agent-policy-transaction-'))
        if (preparedName === undefined) throw new Error('expected prepared sibling')
        const { rename } = await import('node:fs/promises')
        await rename(join(root, 'safe'), movedSafe)
        await symlink(outside, join(root, 'safe'))
        outsideTrapPath = join(outside, preparedName)
        await writeFile(outsideTrapPath, 'outside trap\n')
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })

    expect(result).toMatchObject({ ok: false, code: 'transaction-failed' })
    await expectMissing(join(outside, 'new.md'))
    expect(await readFile(outsideTrapPath, 'utf8')).toBe('outside trap\n')
    expect((await readdir(movedSafe)).some((name) => name.endsWith('.tmp'))).toBe(true)
  })

  it('reports rollback failures prominently with the affected path', async () => {
    const { parent, root } = await sandbox()
    const previous = generated('old\n')
    await writeFile(join(root, 'owned.md'), previous)
    const reviewed = await plan(parent, root, [artifact('owned.md', generated('new\n'))])
    const hooks: TransactionHooks = {
      beforeRename: ({ phase }) => {
        if (phase === 'install') throw new Error('simulated write failure')
        if (phase === 'restore') throw new Error('simulated rollback failure')
      },
    }

    const result = await applyPlan(reviewed, {
      repositoryRoot: root,
      toolkitVersion,
      transactionHooks: hooks,
    })

    expect(result).toMatchObject({ ok: false, code: 'transaction-failed' })
    if (result.ok) throw new Error('expected transaction failure')
    expect(result.message).toMatch(/ROLLBACK FAILED/i)
    expect(result.rollbackFailures).toEqual([
      expect.stringMatching(/owned\.md.*simulated rollback failure/i),
    ])
    expect((await readdir(root)).some((name) => name.includes('.backup'))).toBe(true)
  })

  it('rejects a prior schema-1 plan explicitly before canonical hash processing', async () => {
    const { parent, root } = await sandbox()
    const reviewed = await plan(parent, root, [artifact('new.md', generated('new\n'))])
    const { currentManagedRegionHashes: _newField, ...priorFields } = reviewed
    const priorPlan = { ...priorFields, schemaVersion: '1' } as ChangePlan

    const result = await applyPlan(priorPlan, { repositoryRoot: root, toolkitVersion })

    expect(result).toMatchObject({
      ok: false,
      code: 'invalid-plan',
      message: expect.stringMatching(/unsupported.*schema 1/i),
    })
    await expectMissing(join(root, 'new.md'))
  })
})

describe('drift reconciliation', () => {
  it('returns only a new reviewed-plan proposal for representable adoption', () => {
    const proposal = reconcileDrift('adopt', {
      artifactPath: 'AGENTS.md',
      currentContent: `${start}\nlocally edited intent\n${end}\n`,
      canonicalSourceProposal: {
        path: '.agent-policy/overlays/local.yaml',
        content: 'rules:\n  core/example: disabled\n',
      },
    })

    expect(proposal).toEqual({
      kind: 'replan',
      choice: 'adopt',
      requiresReview: true,
      canonicalSourceChanges: [{
        path: '.agent-policy/overlays/local.yaml',
        content: 'rules:\n  core/example: disabled\n',
      }],
      discardArtifactEdits: false,
    })
    expect(proposal).not.toHaveProperty('planHash')
  })

  it('keeps regenerate, abort, unrepresentable adoption, and non-interactive drift write-free', () => {
    const drift = { artifactPath: 'AGENTS.md', currentContent: 'edited\n' }

    expect(reconcileDrift('regenerate', drift)).toEqual({
      kind: 'replan',
      choice: 'regenerate',
      requiresReview: true,
      canonicalSourceChanges: [],
      discardArtifactEdits: true,
    })
    expect(reconcileDrift('abort', drift)).toEqual({ kind: 'abort' })
    expect(reconcileDrift('adopt', drift)).toMatchObject({
      kind: 'unresolved',
      reason: 'unrepresentable-artifact-intent',
    })
    expect(reconcileDrift(undefined, drift)).toMatchObject({
      kind: 'unresolved',
      reason: 'non-interactive-drift',
    })
  })
})
