import { lstat, readFile, realpath } from 'node:fs/promises'
import { isAbsolute, posix, relative, resolve, sep, win32 } from 'node:path'

import {
  MANAGED_REGION_END,
  MANAGED_REGION_START,
  removeManagedRegion,
} from '../adapters/codex/managed-region.js'
import type { VirtualArtifact } from '../domain/artifacts.js'
import { normalizeGeneratedLineEndings, sha256Utf8 } from './hash.js'

export type ArtifactState =
  | 'clean'
  | 'missing'
  | 'unmanaged'
  | 'managed-drift'
  | 'invalid-marker'

export interface ArtifactInspection {
  readonly path: string
  readonly state: ArtifactState
  readonly currentContent?: string
  readonly currentSha256?: string
  readonly managedRegionSha256?: string
}

const markerPattern = /<!--\s*agent-policy:(?:start\b[^>]*|end\b[^>]*)-->/g
const sentinelPattern = /agent-policy:(?:start|end)/g

interface ManagedRegion {
  readonly kind: 'absent' | 'valid' | 'invalid'
  readonly content?: string
  readonly start?: number
  readonly end?: number
}

function managedRegion(source: string): ManagedRegion {
  const sentinels = [...source.matchAll(sentinelPattern)]
  if (sentinels.length === 0) return { kind: 'absent' }

  const markers = [...source.matchAll(markerPattern)]
  if (markers.length !== sentinels.length) return { kind: 'invalid' }
  if (markers.some(([marker]) => marker !== MANAGED_REGION_START && marker !== MANAGED_REGION_END)) {
    return { kind: 'invalid' }
  }

  const starts = markers.filter(([marker]) => marker === MANAGED_REGION_START)
  const ends = markers.filter(([marker]) => marker === MANAGED_REGION_END)
  const startIndex = starts[0]?.index
  const endIndex = ends[0]?.index
  if (
    starts.length !== 1
    || ends.length !== 1
    || startIndex === undefined
    || endIndex === undefined
    || startIndex >= endIndex
  ) {
    return { kind: 'invalid' }
  }
  return {
    kind: 'valid',
    content: source.slice(startIndex, endIndex + MANAGED_REGION_END.length),
    start: startIndex,
    end: endIndex + MANAGED_REGION_END.length,
  }
}

function generatedOwnershipMarker(owner: string): string {
  return `<!--\nGenerated by ${owner}.\n`
}

function hasGeneratedOwnershipHeader(content: string, owner: string): boolean {
  const stable = content.replace(/\r\n/g, '\n')
  const marker = generatedOwnershipMarker(owner)
  if (stable.startsWith(marker)) return true

  const frontmatter = /^---\n[\s\S]*?\n---\n\n/.exec(stable)
  if (frontmatter !== null && stable.slice(frontmatter[0].length).startsWith(marker)) return true
  try {
    const parsed = JSON.parse(stable) as { readonly generatedBy?: unknown; readonly artifactHash?: unknown }
    return parsed.generatedBy === owner && typeof parsed.artifactHash === 'string'
  } catch {
    return false
  }
}

function isOutside(root: string, candidate: string): boolean {
  const offset = relative(root, candidate)
  return offset === '..' || offset.startsWith(`..${sep}`) || isAbsolute(offset)
}

export function normalizeArtifactPath(input: string): string {
  if (
    input.length === 0
    || input.includes('\0')
    || input.includes('\\')
    || posix.isAbsolute(input)
    || win32.isAbsolute(input)
  ) {
    throw new Error(`Invalid artifact path: ${JSON.stringify(input)}`)
  }
  const segments = input.split('/')
  if (segments.includes('..')) {
    throw new Error(`Invalid artifact path traversal: ${JSON.stringify(input)}`)
  }
  const normalized = posix.normalize(input).replace(/^\.\//, '')
  if (normalized === '.' || normalized.length === 0 || normalized.startsWith('../')) {
    throw new Error(`Invalid artifact path: ${JSON.stringify(input)}`)
  }
  return normalized
}

/** Resolve a repository-relative path after proving each existing symlink stays confined. */
export async function resolveConfinedPath(
  repositoryRoot: string,
  artifactPath: string,
): Promise<{ readonly repositoryRoot: string; readonly path: string }> {
  const normalized = normalizeArtifactPath(artifactPath)
  const root = await realpath(repositoryRoot)
  const target = resolve(root, ...normalized.split('/'))
  if (isOutside(root, target)) throw new Error(`Artifact path is outside repository: ${artifactPath}`)

  let cursor = root
  for (const segment of normalized.split('/')) {
    cursor = resolve(cursor, segment)
    try {
      const metadata = await lstat(cursor)
      if (metadata.isSymbolicLink()) {
        const resolved = await realpath(cursor)
        if (isOutside(root, resolved)) {
          throw new Error(`Artifact path escapes repository through symlink: ${artifactPath}`)
        }
      }
    } catch (error) {
      if ((error as NodeJS.ErrnoException).code === 'ENOENT') break
      throw error
    }
  }
  return { repositoryRoot: root, path: target }
}

export async function inspectArtifact(
  repositoryRoot: string,
  artifact: VirtualArtifact,
): Promise<ArtifactInspection> {
  const normalized = normalizeArtifactPath(artifact.path)
  const desiredRegion = artifact.operation === 'managed-region'
    ? managedRegion(artifact.content)
    : undefined
  if (desiredRegion !== undefined && desiredRegion.kind !== 'valid') {
    throw new Error(`Invalid desired Managed Region in artifact: ${normalized}`)
  }
  const target = await resolveConfinedPath(repositoryRoot, normalized)
  let currentContent: string
  try {
    currentContent = await readFile(target.path, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return { path: normalized, state: 'missing' }
    }
    throw error
  }

  const currentSha256 = sha256Utf8(currentContent)
  if (artifact.operation === 'managed-region-remove') {
    const currentRegion = managedRegion(currentContent)
    if (currentRegion.kind === 'invalid') {
      return { path: normalized, state: 'invalid-marker', currentContent, currentSha256 }
    }
    if (currentRegion.kind === 'absent') {
      return {
        path: normalized,
        state: currentContent === artifact.content ? 'clean' : 'unmanaged',
        currentContent,
        currentSha256,
      }
    }
    const withoutRegion = removeManagedRegion(currentContent) ?? currentContent
    return {
      path: normalized,
      state: normalizeGeneratedLineEndings(withoutRegion) === normalizeGeneratedLineEndings(artifact.content)
        ? 'clean'
        : 'managed-drift',
      currentContent,
      currentSha256,
      managedRegionSha256: sha256Utf8(currentRegion.content ?? ''),
    }
  }

  if (artifact.operation !== 'managed-region') {
    if (
      currentSha256 === artifact.sha256 && currentContent === artifact.content
      || hasGeneratedOwnershipHeader(currentContent, artifact.owner)
        && normalizeGeneratedLineEndings(currentContent) === normalizeGeneratedLineEndings(artifact.content)
    ) {
      return { path: normalized, state: 'clean', currentContent, currentSha256 }
    }
    return {
      path: normalized,
      state: hasGeneratedOwnershipHeader(currentContent, artifact.owner)
        ? 'managed-drift'
        : 'unmanaged',
      currentContent,
      currentSha256,
    }
  }

  const currentRegion = managedRegion(currentContent)
  if (currentRegion.kind === 'invalid') {
    return { path: normalized, state: 'invalid-marker', currentContent, currentSha256 }
  }
  if (currentRegion.kind === 'absent') {
    return { path: normalized, state: 'unmanaged', currentContent, currentSha256 }
  }
  const managedRegionSha256 = sha256Utf8(currentRegion.content ?? '')
  return {
    path: normalized,
    state: normalizeGeneratedLineEndings(currentRegion.content ?? '')
      === normalizeGeneratedLineEndings(desiredRegion?.content ?? '')
      ? 'clean'
      : 'managed-drift',
    currentContent,
    currentSha256,
    managedRegionSha256,
  }
}
