import { readFile, realpath } from 'node:fs/promises'

import type { VirtualArtifact } from '../domain/artifacts.js'
import type { ChangePlan } from '../domain/change-plan.js'
import { sha256Utf8 } from '../planner/hash.js'
import {
  inspectArtifact,
  normalizeArtifactPath,
  resolveConfinedPath,
} from '../planner/inspect.js'
import { computePlanHash } from '../planner/serialize-plan.js'

const toolkitOwner = '@agent-policy/agent-policy-toolkit'

export type ApplyFailureCode =
  | 'invalid-plan'
  | 'repository-mismatch'
  | 'toolkit-mismatch'
  | 'source-drift'
  | 'artifact-drift'
  | 'ownership-drift'
  | 'unsafe-target'

export interface ApplyFailure {
  readonly ok: false
  readonly code: ApplyFailureCode
  readonly message: string
  readonly paths: readonly string[]
}

export interface PreparedOperation {
  readonly relativePath: string
  readonly targetPath: string
  readonly content?: string
  readonly existed: boolean
  readonly expectedCurrentSha256?: string
}

export interface ValidatedApplication {
  readonly repositoryRoot: string
  readonly operations: readonly PreparedOperation[]
}

export interface PreconditionsOptions {
  readonly repositoryRoot: string
  readonly toolkitVersion: string
}

function failure(
  code: ApplyFailureCode,
  message: string,
  paths: readonly string[] = [],
): ApplyFailure {
  return { ok: false, code, message, paths }
}

function compareStrings(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0
}

async function readCurrent(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined
    throw error
  }
}

function exactKeys(values: Readonly<Record<string, string>>): readonly string[] {
  return Object.keys(values).sort(compareStrings)
}

function hasExactGeneratedOwnership(content: string, owner: string): boolean {
  const header = `<!--\nGenerated by ${owner}.\n`
  if (content.startsWith(header)) return true
  const frontmatter = /^---\n[\s\S]*?\n---\n\n/.exec(content)
  return frontmatter !== null && content.slice(frontmatter[0].length).startsWith(header)
}

function hasExactManagedRegionOwnership(content: string, owner: string): boolean {
  const expectedStart = `<!-- agent-policy:start owner=${owner} -->`
  const expectedEnd = '<!-- agent-policy:end -->'
  const sentinels = [...content.matchAll(/agent-policy:(?:start|end)/g)]
  const markers = [...content.matchAll(/<!--\s*agent-policy:(?:start\b[^>]*|end\b[^>]*)-->/g)]
  if (sentinels.length !== 2 || markers.length !== 2) return false
  const [startMarker, endMarker] = markers
  return startMarker?.[0] === expectedStart
    && endMarker?.[0] === expectedEnd
    && (startMarker.index ?? -1) < (endMarker.index ?? -1)
}

function validatePlanShape(plan: ChangePlan): ApplyFailure | undefined {
  if (plan.schemaVersion !== '2') {
    return failure('invalid-plan', `Unsupported Change Plan schema ${plan.schemaVersion}`)
  }
  if (computePlanHash(plan) !== plan.planHash) {
    return failure('invalid-plan', 'Change Plan hash does not match its canonical contents')
  }

  const desiredPaths = plan.desiredArtifacts.map(({ path }) => path)
  const allTargets = [...desiredPaths, ...plan.removals]
  const allPaths = [
    ...Object.keys(plan.sourceHashes),
    ...allTargets,
    ...Object.keys(plan.currentArtifactHashes),
    ...Object.keys(plan.currentManagedRegionHashes),
  ]
  for (const path of allPaths) {
    if (normalizeArtifactPath(path) !== path) {
      return failure('invalid-plan', `Change Plan path is not canonical: ${path}`, [path])
    }
  }
  if (new Set(allTargets).size !== allTargets.length) {
    return failure('invalid-plan', 'Change Plan contains duplicate targets', allTargets)
  }
  for (const artifact of plan.desiredArtifacts) {
    if (artifact.operation === 'delete') {
      return failure('invalid-plan', 'Delete artifacts must be represented as removals', [artifact.path])
    }
    if (artifact.sha256 !== sha256Utf8(artifact.content)) {
      return failure('invalid-plan', `Desired artifact hash mismatch for ${artifact.path}`, [artifact.path])
    }
    if (artifact.owner !== toolkitOwner) {
      return failure('invalid-plan', `Unexpected artifact owner for ${artifact.path}`, [artifact.path])
    }
    const desiredIsOwned = artifact.operation === 'managed-region'
      ? hasExactManagedRegionOwnership(artifact.content, artifact.owner)
      : hasExactGeneratedOwnership(artifact.content, artifact.owner)
    if (!desiredIsOwned) {
      return failure('invalid-plan', `Desired artifact is missing exact ownership: ${artifact.path}`, [artifact.path])
    }
  }

  const expectedCurrent = new Set<string>()
  for (const artifact of plan.desiredArtifacts) {
    if (
      artifact.operation === 'replace'
      || (
        artifact.operation === 'managed-region'
        && plan.currentArtifactHashes[artifact.path] !== undefined
      )
    ) {
      expectedCurrent.add(artifact.path)
    }
  }
  for (const path of plan.removals) expectedCurrent.add(path)
  if (
    exactKeys(plan.currentArtifactHashes).join('\0')
    !== [...expectedCurrent].sort(compareStrings).join('\0')
  ) {
    return failure('invalid-plan', 'Change Plan current artifact preconditions are incomplete or extraneous')
  }

  const managedPaths = new Set(
    plan.desiredArtifacts
      .filter(({ operation }) => operation === 'managed-region')
      .map(({ path }) => path),
  )
  if (exactKeys(plan.currentManagedRegionHashes).some((path) => !managedPaths.has(path))) {
    return failure('invalid-plan', 'Change Plan contains an extraneous Managed Region precondition')
  }
  return undefined
}

async function resolveEveryPath(
  repositoryRoot: string,
  plan: ChangePlan,
): Promise<ReadonlyMap<string, string> | ApplyFailure> {
  const resolved = new Map<string, string>()
  const paths = [
    ...Object.keys(plan.sourceHashes),
    ...plan.desiredArtifacts.map(({ path }) => path),
    ...plan.removals,
    ...Object.keys(plan.currentArtifactHashes),
    ...Object.keys(plan.currentManagedRegionHashes),
  ]
  try {
    for (const path of paths) {
      resolved.set(path, (await resolveConfinedPath(repositoryRoot, path)).path)
    }
  } catch (error) {
    return failure(
      'unsafe-target',
      `Unsafe Change Plan path: ${error instanceof Error ? error.message : String(error)}`,
    )
  }
  return resolved
}

/** Revalidate every immutable plan and filesystem precondition without mutating the repository. */
export async function revalidatePreconditions(
  plan: ChangePlan,
  options: PreconditionsOptions,
): Promise<ValidatedApplication | ApplyFailure> {
  let shapeFailure: ApplyFailure | undefined
  try {
    shapeFailure = validatePlanShape(plan)
  } catch (error) {
    return failure(
      'invalid-plan',
      `Invalid Change Plan: ${error instanceof Error ? error.message : String(error)}`,
    )
  }
  if (shapeFailure !== undefined) return shapeFailure

  let repositoryRoot: string
  try {
    repositoryRoot = await realpath(options.repositoryRoot)
  } catch (error) {
    return failure(
      'repository-mismatch',
      `Cannot resolve repository root: ${error instanceof Error ? error.message : String(error)}`,
    )
  }
  if (sha256Utf8(repositoryRoot) !== plan.repositoryRootFingerprint) {
    return failure('repository-mismatch', 'Change Plan was generated for another repository root')
  }
  if (plan.toolkitVersion !== options.toolkitVersion) {
    return failure(
      'toolkit-mismatch',
      `Change Plan toolkit version ${plan.toolkitVersion} does not match ${options.toolkitVersion}`,
    )
  }

  const resolved = await resolveEveryPath(repositoryRoot, plan)
  if ('ok' in resolved) return resolved

  const sourceDrift: string[] = []
  for (const [path, expectedHash] of Object.entries(plan.sourceHashes)) {
    const current = await readCurrent(resolved.get(path) ?? '')
    if (current === undefined || sha256Utf8(current) !== expectedHash) sourceDrift.push(path)
  }
  if (sourceDrift.length > 0) {
    return failure('source-drift', 'Canonical policy sources changed after plan review', sourceDrift)
  }

  const operations: PreparedOperation[] = []
  for (const artifact of [...plan.desiredArtifacts].sort((left, right) =>
    compareStrings(left.path, right.path))) {
    const targetPath = resolved.get(artifact.path) ?? ''
    const current = await readCurrent(targetPath)
    const expectedHash = plan.currentArtifactHashes[artifact.path]
    if (expectedHash === undefined) {
      if (current !== undefined) {
        return failure('artifact-drift', `Target appeared after review: ${artifact.path}`, [artifact.path])
      }
      operations.push({
        relativePath: artifact.path,
        targetPath,
        content: artifact.content,
        existed: false,
      })
      continue
    }
    if (current === undefined || sha256Utf8(current) !== expectedHash) {
      return failure('artifact-drift', `Artifact changed after review: ${artifact.path}`, [artifact.path])
    }

    const ownership = await inspectArtifact(repositoryRoot, artifact)
    if (artifact.operation === 'managed-region') {
      const expectedRegionHash = plan.currentManagedRegionHashes[artifact.path]
      if (expectedRegionHash === undefined) {
        if (ownership.state !== 'unmanaged') {
          return failure('ownership-drift', `Managed Region ownership changed: ${artifact.path}`, [artifact.path])
        }
      } else if (ownership.managedRegionSha256 === undefined) {
        return failure('ownership-drift', `Managed Region ownership changed: ${artifact.path}`, [artifact.path])
      } else if (ownership.managedRegionSha256 !== expectedRegionHash) {
        return failure('artifact-drift', `Managed Region changed after review: ${artifact.path}`, [artifact.path])
      }
    } else if (!hasExactGeneratedOwnership(current, artifact.owner)) {
      return failure('ownership-drift', `Generated artifact ownership changed: ${artifact.path}`, [artifact.path])
    }
    operations.push({
      relativePath: artifact.path,
      targetPath,
      content: artifact.content,
      existed: true,
      expectedCurrentSha256: expectedHash,
    })
  }

  for (const path of [...plan.removals].sort(compareStrings)) {
    const targetPath = resolved.get(path) ?? ''
    const current = await readCurrent(targetPath)
    if (current === undefined || sha256Utf8(current) !== plan.currentArtifactHashes[path]) {
      return failure('artifact-drift', `Removal target changed after review: ${path}`, [path])
    }
    if (!hasExactGeneratedOwnership(current, toolkitOwner)) {
      return failure('ownership-drift', `Refusing to remove an unowned artifact: ${path}`, [path])
    }
    operations.push({
      relativePath: path,
      targetPath,
      existed: true,
      expectedCurrentSha256: plan.currentArtifactHashes[path],
    })
  }

  return { repositoryRoot, operations }
}
