import { readFile, realpath } from 'node:fs/promises'

import type { VirtualArtifact } from '../domain/artifacts.js'
import type { ChangePlan } from '../domain/change-plan.js'
import { sha256Utf8 } from '../planner/hash.js'
import {
  inspectArtifact,
  normalizeArtifactPath,
  resolveConfinedPath,
} from '../planner/inspect.js'
import { computePlanHash } from '../planner/serialize-plan.js'

const toolkitOwner = '@agent-policy/agent-policy-toolkit'

export type ApplyFailureCode =
  | 'invalid-plan'
  | 'repository-mismatch'
  | 'toolkit-mismatch'
  | 'source-drift'
  | 'artifact-drift'
  | 'ownership-drift'
  | 'unsafe-target'

export interface ApplyFailure {
  readonly ok: false
  readonly code: ApplyFailureCode
  readonly message: string
  readonly paths: readonly string[]
}

export interface PreparedOperation {
  readonly relativePath: string
  readonly targetPath: string
  readonly content?: string
  readonly existed: boolean
  readonly expectedCurrentSha256?: string
  /** Source replacement is intentionally rechecked before backup, not while its backup is visible. */
  readonly skipPreInstallRecheck?: boolean
}

export interface ValidatedApplication {
  readonly repositoryRoot: string
  readonly operations: readonly PreparedOperation[]
}

export interface PreconditionsOptions {
  readonly repositoryRoot: string
  readonly toolkitVersion: string
}

/** Recheck reviewed plan identity, repository identity, toolkit version, and source bytes. */
export async function revalidateImmutablePreconditions(
  plan: ChangePlan,
  options: PreconditionsOptions,
  installedCreatePaths: readonly string[] = [],
): Promise<ApplyFailure | undefined> {
  try {
    const shapeFailure = validatePlanShape(plan)
    if (shapeFailure !== undefined) return shapeFailure
    const repositoryRoot = await realpath(options.repositoryRoot)
    if (sha256Utf8(repositoryRoot) !== plan.repositoryRootFingerprint) {
      return failure('repository-mismatch', 'Change Plan was generated for another repository root')
    }
    if (plan.toolkitVersion !== options.toolkitVersion) {
      return failure(
        'toolkit-mismatch',
        `Change Plan toolkit version ${plan.toolkitVersion} does not match ${options.toolkitVersion}`,
      )
    }
    const sourceDrift: string[] = []
    const installedCreates = new Set(installedCreatePaths)
    for (const [path, expectedHash] of Object.entries(plan.sourceHashes)) {
      const target = await resolveConfinedPath(repositoryRoot, path)
      const current = await readCurrent(target.path)
      if (current === undefined || sha256Utf8(current) !== expectedHash) sourceDrift.push(path)
    }
    for (const source of plan.sourceChanges ?? []) {
      if (source.operation !== 'create') continue
      const target = await resolveConfinedPath(repositoryRoot, source.path)
      const current = await readCurrent(target.path)
      if (
        installedCreates.has(source.path)
          ? current === undefined || sha256Utf8(current) !== source.sha256
          : current !== undefined
      ) sourceDrift.push(source.path)
    }
    return sourceDrift.length === 0
      ? undefined
      : failure('source-drift', 'Canonical policy sources changed after plan review', sourceDrift)
  } catch (error) {
    return failure(
      'invalid-plan',
      `Invalid immutable Change Plan precondition: ${error instanceof Error ? error.message : String(error)}`,
    )
  }
}

function failure(
  code: ApplyFailureCode,
  message: string,
  paths: readonly string[] = [],
): ApplyFailure {
  return { ok: false, code, message, paths }
}

function compareStrings(left: string, right: string): number {
  return left < right ? -1 : left > right ? 1 : 0
}

async function readCurrent(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined
    throw error
  }
}

function exactKeys(values: Readonly<Record<string, string>>): readonly string[] {
  return Object.keys(values).sort(compareStrings)
}

function hasExactGeneratedOwnership(content: string, owner: string): boolean {
  const stable = content.replace(/\r\n/g, '\n')
  const header = `<!--\nGenerated by ${owner}.\n`
  if (stable.startsWith(header)) return true
  const frontmatter = /^---\n[\s\S]*?\n---\n\n/.exec(stable)
  if (frontmatter !== null && stable.slice(frontmatter[0].length).startsWith(header)) return true
  try {
    const parsed = JSON.parse(stable) as { readonly generatedBy?: unknown; readonly artifactHash?: unknown }
    return parsed.generatedBy === owner && typeof parsed.artifactHash === 'string'
  } catch {
    return false
  }
}

function hasExactManagedRegionOwnership(content: string, owner: string): boolean {
  const expectedStart = `<!-- agent-policy:start owner=${owner} -->`
  const expectedEnd = '<!-- agent-policy:end -->'
  const sentinels = [...content.matchAll(/agent-policy:(?:start|end)/g)]
  const markers = [...content.matchAll(/<!--\s*agent-policy:(?:start\b[^>]*|end\b[^>]*)-->/g)]
  if (sentinels.length !== 2 || markers.length !== 2) return false
  const [startMarker, endMarker] = markers
  return startMarker?.[0] === expectedStart
    && endMarker?.[0] === expectedEnd
    && (startMarker.index ?? -1) < (endMarker.index ?? -1)
}

function validatePlanShape(plan: ChangePlan): ApplyFailure | undefined {
  if (plan.schemaVersion !== '1') {
    return failure('invalid-plan', `Unsupported Change Plan schema ${plan.schemaVersion}`)
  }
  if (computePlanHash(plan) !== plan.planHash) {
    return failure('invalid-plan', 'Change Plan hash does not match its canonical contents')
  }

  const desiredPaths = plan.desiredArtifacts.map(({ path }) => path)
  const allTargets = [...desiredPaths, ...plan.removals]
  const sourceChanges = plan.sourceChanges ?? []
  const sourceChangePaths = sourceChanges.map(({ path }) => path)
  const allPaths = [
    ...Object.keys(plan.sourceHashes),
    ...sourceChangePaths,
    ...allTargets,
    ...Object.keys(plan.currentArtifactHashes),
    ...Object.keys(plan.currentManagedRegionHashes ?? {}),
  ]
  for (const path of allPaths) {
    if (normalizeArtifactPath(path) !== path) {
      return failure('invalid-plan', `Change Plan path is not canonical: ${path}`, [path])
    }
  }
  if (new Set(sourceChangePaths).size !== sourceChangePaths.length) {
    return failure('invalid-plan', 'Change Plan contains duplicate canonical source changes', sourceChangePaths)
  }
  for (const source of sourceChanges) {
    if (source.operation !== 'create' && source.operation !== 'replace') {
      return failure('invalid-plan', `Unsupported canonical source operation: ${source.path}`, [source.path])
    }
    if (source.operation === 'replace' && plan.sourceHashes[source.path] === undefined) {
      return failure('invalid-plan', `Source replacement is not bound to a canonical source: ${source.path}`, [source.path])
    }
    if (source.operation === 'create' && plan.sourceHashes[source.path] !== undefined) {
      return failure('invalid-plan', `Source creation must be bound to canonical source absence: ${source.path}`, [source.path])
    }
    if (source.sha256 !== sha256Utf8(source.content)) {
      return failure('invalid-plan', `Canonical source hash mismatch for ${source.path}`, [source.path])
    }
  }
  if (new Set(allTargets).size !== allTargets.length) {
    return failure('invalid-plan', 'Change Plan contains duplicate targets', allTargets)
  }
  if (sourceChangePaths.some((path) => allTargets.includes(path))) {
    return failure('invalid-plan', 'Canonical source changes cannot overlap generated or removed targets', sourceChangePaths)
  }
  for (const artifact of plan.desiredArtifacts) {
    if (artifact.operation === 'delete') {
      return failure('invalid-plan', 'Delete artifacts must be represented as removals', [artifact.path])
    }
    if (artifact.sha256 !== sha256Utf8(artifact.content)) {
      return failure('invalid-plan', `Desired artifact hash mismatch for ${artifact.path}`, [artifact.path])
    }
    if (artifact.owner !== toolkitOwner) {
      return failure('invalid-plan', `Unexpected artifact owner for ${artifact.path}`, [artifact.path])
    }
    const desiredIsOwned = artifact.operation === 'managed-region'
      ? hasExactManagedRegionOwnership(artifact.content, artifact.owner)
      : artifact.operation === 'managed-region-remove'
        ? !/agent-policy:(?:start|end)/.test(artifact.content)
        : hasExactGeneratedOwnership(artifact.content, artifact.owner)
    if (!desiredIsOwned) {
      return failure('invalid-plan', `Desired artifact is missing exact ownership: ${artifact.path}`, [artifact.path])
    }
  }

  const expectedCurrent = new Set<string>()
  for (const artifact of plan.desiredArtifacts) {
    if (
      artifact.operation === 'replace'
      || (
        (artifact.operation === 'managed-region' || artifact.operation === 'managed-region-remove')
        && plan.currentArtifactHashes[artifact.path] !== undefined
      )
    ) {
      expectedCurrent.add(artifact.path)
    }
  }
  for (const path of plan.removals) expectedCurrent.add(path)
  if (
    exactKeys(plan.currentArtifactHashes).join('\0')
    !== [...expectedCurrent].sort(compareStrings).join('\0')
  ) {
    return failure('invalid-plan', 'Change Plan current artifact preconditions are incomplete or extraneous')
  }

  const managedPaths = new Set(
    plan.desiredArtifacts
      .filter(({ operation }) => operation === 'managed-region' || operation === 'managed-region-remove')
      .map(({ path }) => path),
  )
  if (exactKeys(plan.currentManagedRegionHashes ?? {}).some((path) => !managedPaths.has(path))) {
    return failure('invalid-plan', 'Change Plan contains an extraneous Managed Region precondition')
  }
  return undefined
}

async function resolveEveryPath(
  repositoryRoot: string,
  plan: ChangePlan,
): Promise<ReadonlyMap<string, string> | ApplyFailure> {
  const resolved = new Map<string, string>()
  const paths = [
    ...Object.keys(plan.sourceHashes),
    ...(plan.sourceChanges ?? []).map(({ path }) => path),
    ...plan.desiredArtifacts.map(({ path }) => path),
    ...plan.removals,
    ...Object.keys(plan.currentArtifactHashes),
    ...Object.keys(plan.currentManagedRegionHashes ?? {}),
  ]
  try {
    for (const path of paths) {
      resolved.set(path, (await resolveConfinedPath(repositoryRoot, path)).path)
    }
  } catch (error) {
    return failure(
      'unsafe-target',
      `Unsafe Change Plan path: ${error instanceof Error ? error.message : String(error)}`,
    )
  }
  return resolved
}

/** Revalidate every immutable plan and filesystem precondition without mutating the repository. */
export async function revalidatePreconditions(
  plan: ChangePlan,
  options: PreconditionsOptions,
): Promise<ValidatedApplication | ApplyFailure> {
  let shapeFailure: ApplyFailure | undefined
  try {
    shapeFailure = validatePlanShape(plan)
  } catch (error) {
    return failure(
      'invalid-plan',
      `Invalid Change Plan: ${error instanceof Error ? error.message : String(error)}`,
    )
  }
  if (shapeFailure !== undefined) return shapeFailure

  let repositoryRoot: string
  try {
    repositoryRoot = await realpath(options.repositoryRoot)
  } catch (error) {
    return failure(
      'repository-mismatch',
      `Cannot resolve repository root: ${error instanceof Error ? error.message : String(error)}`,
    )
  }
  if (sha256Utf8(repositoryRoot) !== plan.repositoryRootFingerprint) {
    return failure('repository-mismatch', 'Change Plan was generated for another repository root')
  }
  if (plan.toolkitVersion !== options.toolkitVersion) {
    return failure(
      'toolkit-mismatch',
      `Change Plan toolkit version ${plan.toolkitVersion} does not match ${options.toolkitVersion}`,
    )
  }

  const resolved = await resolveEveryPath(repositoryRoot, plan)
  if ('ok' in resolved) return resolved

  const sourceDrift: string[] = []
  for (const [path, expectedHash] of Object.entries(plan.sourceHashes)) {
    const current = await readCurrent(resolved.get(path) ?? '')
    if (current === undefined || sha256Utf8(current) !== expectedHash) sourceDrift.push(path)
  }
  for (const source of plan.sourceChanges ?? []) {
    if (source.operation !== 'create') continue
    if (await readCurrent(resolved.get(source.path) ?? '') !== undefined) sourceDrift.push(source.path)
  }
  if (sourceDrift.length > 0) {
    return failure('source-drift', 'Canonical policy sources changed after plan review', sourceDrift)
  }

  const operations: PreparedOperation[] = []
  for (const artifact of [...plan.desiredArtifacts].sort((left, right) =>
    compareStrings(left.path, right.path))) {
    const targetPath = resolved.get(artifact.path) ?? ''
    const current = await readCurrent(targetPath)
    const expectedHash = plan.currentArtifactHashes[artifact.path]
    if (expectedHash === undefined) {
      if (artifact.operation === 'managed-region-remove') {
        return failure('invalid-plan', `Managed Region removal requires an existing target: ${artifact.path}`, [artifact.path])
      }
      if (current !== undefined) {
        return failure('artifact-drift', `Target appeared after review: ${artifact.path}`, [artifact.path])
      }
      operations.push({
        relativePath: artifact.path,
        targetPath,
        content: artifact.content,
        existed: false,
      })
      continue
    }
    if (current === undefined || sha256Utf8(current) !== expectedHash) {
      return failure('artifact-drift', `Artifact changed after review: ${artifact.path}`, [artifact.path])
    }

    const ownership = await inspectArtifact(repositoryRoot, artifact)
    if (artifact.operation === 'managed-region' || artifact.operation === 'managed-region-remove') {
      const expectedRegionHash = plan.currentManagedRegionHashes?.[artifact.path]
      if (artifact.operation === 'managed-region-remove' && !hasExactManagedRegionOwnership(current, artifact.owner)) {
        return failure('ownership-drift', `Managed Region ownership changed: ${artifact.path}`, [artifact.path])
      }
      if (artifact.operation === 'managed-region-remove' && ownership.state !== 'clean') {
        return failure('ownership-drift', `Managed Region removal would alter unmanaged text: ${artifact.path}`, [artifact.path])
      }
      if (expectedRegionHash === undefined) {
        const legacyOwnedRegion = plan.currentManagedRegionHashes === undefined
          && ownership.managedRegionSha256 !== undefined
          && ownership.state !== 'invalid-marker'
        if (!legacyOwnedRegion && ownership.state !== 'unmanaged') {
          return failure('ownership-drift', `Managed Region ownership changed: ${artifact.path}`, [artifact.path])
        }
      } else if (ownership.managedRegionSha256 === undefined) {
        return failure('ownership-drift', `Managed Region ownership changed: ${artifact.path}`, [artifact.path])
      } else if (ownership.managedRegionSha256 !== expectedRegionHash) {
        return failure('artifact-drift', `Managed Region changed after review: ${artifact.path}`, [artifact.path])
      }
    } else if (!hasExactGeneratedOwnership(current, artifact.owner)) {
      return failure('ownership-drift', `Generated artifact ownership changed: ${artifact.path}`, [artifact.path])
    }
    operations.push({
      relativePath: artifact.path,
      targetPath,
      content: artifact.operation === 'managed-region-remove' && artifact.content.length === 0
        ? undefined
        : artifact.content,
      existed: true,
      expectedCurrentSha256: expectedHash,
    })
  }

  for (const path of [...plan.removals].sort(compareStrings)) {
    const targetPath = resolved.get(path) ?? ''
    const current = await readCurrent(targetPath)
    if (current === undefined || sha256Utf8(current) !== plan.currentArtifactHashes[path]) {
      return failure('artifact-drift', `Removal target changed after review: ${path}`, [path])
    }
    if (!hasExactGeneratedOwnership(current, toolkitOwner)) {
      return failure('ownership-drift', `Refusing to remove an unowned artifact: ${path}`, [path])
    }
    operations.push({
      relativePath: path,
      targetPath,
      existed: true,
      expectedCurrentSha256: plan.currentArtifactHashes[path],
    })
  }

  // Install canonical source writes last. The transaction rechecks the
  // reviewed preconditions between each operation; keeping source mutation at
  // the end means those checks never observe our own in-flight source write.
  for (const source of [...(plan.sourceChanges ?? [])].sort((left, right) =>
    compareStrings(left.path, right.path))) {
    const targetPath = resolved.get(source.path) ?? ''
    const current = await readCurrent(targetPath)
    if (source.operation === 'create') {
      if (current !== undefined) {
        return failure('source-drift', `Canonical policy source changed after review: ${source.path}`, [source.path])
      }
      operations.push({
        relativePath: source.path,
        targetPath,
        content: source.content,
        existed: false,
      })
      continue
    }
    const expectedHash = plan.sourceHashes[source.path]
    if (expectedHash === undefined || current === undefined || sha256Utf8(current) !== expectedHash) {
      return failure('source-drift', `Canonical policy source changed after review: ${source.path}`, [source.path])
    }
    operations.push({
      relativePath: source.path,
      targetPath,
      content: source.content,
      existed: true,
      expectedCurrentSha256: expectedHash,
      skipPreInstallRecheck: true,
    })
  }

  return { repositoryRoot, operations }
}
