import { createHash } from 'node:crypto'

import { renderBundle } from '../../compiler/render-bundle.js'
import type { Bundle } from '../../domain/policy.js'
import type { VirtualArtifact } from '../../domain/artifacts.js'
import type { HarnessAdapter, ProjectionInput } from '../types.js'
import type { CanonicalWorkflowSkill } from '../../catalog/load-catalog.js'
import { codexCapabilities } from './capabilities.js'
import {
  MANAGED_REGION_END,
  MANAGED_REGION_START,
  projectManagedRegion,
} from './managed-region.js'
import {
  ARTIFACT_HASH_PLACEHOLDER,
  materializeArtifactHash,
} from '../../planner/hash.js'

const owner = '@agent-policy/agent-policy-toolkit'

function sha256(content: string): string {
  return createHash('sha256').update(content, 'utf8').digest('hex')
}

function rootBodyTemplate(input: ProjectionInput): string {
  const core = input.bundles.get('core')
  if (core === undefined) throw new Error('Codex projection requires the Core Policy Bundle')

  const sections = [
    `<!--
Generated by ${owner}.
Toolkit version: ${input.toolkitVersion}
Adapter knowledge version: ${codexCapabilities.adapterKnowledgeVersion}
Canonical source hash: ${input.canonicalSourceHash}
Artifact hash: ${ARTIFACT_HASH_PLACEHOLDER}
Do not edit; change \`.agent-policy/\` and regenerate.
-->`,
    '# Agent Policy',
    `## Core policy\n\n${renderBundle(core, input.resolvedPolicy, 'core')}`,
  ]
  const repositoryInvariants = input.repositoryInvariants ?? []
  if (repositoryInvariants.length > 0) {
    sections.push(`## Repository invariants\n\n${repositoryInvariants.join('\n\n')}`)
  }
  sections.push('## Capability routing\n\nUse a generated skill under `.agents/skills/` when its description matches the task, and honor its exclusions before loading it.')
  return sections.join('\n\n')
}

function rootBody(input: ProjectionInput): string {
  const placeholderRegion = `${MANAGED_REGION_START}\n${rootBodyTemplate(input)}\n${MANAGED_REGION_END}`
  const region = materializeArtifactHash(placeholderRegion)
  const prefix = `${MANAGED_REGION_START}\n`
  const suffix = `\n${MANAGED_REGION_END}`
  return region.slice(prefix.length, -suffix.length)
}

function hintValues(bundle: Bundle, key: string): readonly string[] {
  const value = bundle.applicability[key]
  return Array.isArray(value) && value.every((item) => typeof item === 'string') ? value : []
}

function list(values: readonly string[]): string {
  return values.join(', ')
}

function skillDescription(bundle: Bundle, input: ProjectionInput): string {
  const technologies = hintValues(bundle, 'technologies')
  const taskIntents = hintValues(bundle, 'taskIntents')
  const filePatterns = hintValues(bundle, 'filePatterns')
  const exclusions = hintValues(bundle, 'exclusions')
  const sentences = [bundle.description]

  if (technologies.length > 0 || taskIntents.length > 0 || filePatterns.length > 0) {
    const positives = [
      technologies.length > 0 ? `technologies ${list(technologies)}` : undefined,
      taskIntents.length > 0 ? `task intents ${list(taskIntents)}` : undefined,
      filePatterns.length > 0 ? `files matching ${list(filePatterns)}` : undefined,
    ].filter((value): value is string => value !== undefined)
    sentences.push(`Use when work involves ${positives.join('; ')}.`)
  }
  if (exclusions.length > 0) sentences.push(`Do not use for ${list(exclusions)}.`)
  if (bundle.dependencies.length > 0) {
    const dependencies = bundle.dependencies.map((dependency) => `${dependency} policy bundle`)
    sentences.push(`Requires the ${dependencies.join(', ')}.`)
  }

  for (const profile of input.scopedProfiles ?? []) {
    if (!profile.bundleIds.includes(bundle.id)) continue
    const workspaces = profile.workspaces ?? []
    const scope = [
      profile.paths.length > 0 ? `paths ${list(profile.paths)}` : undefined,
      workspaces.length > 0 ? `workspaces ${list(workspaces)}` : undefined,
    ].filter((value): value is string => value !== undefined)
    sentences.push(`Scoped profile ${profile.id} applies to ${scope.join(' and ')}.`)
  }

  return sentences.join(' ')
}

function generatedHeader(input: ProjectionInput): string {
  return `<!--
Generated by ${owner}.
Toolkit version: ${input.toolkitVersion}
Adapter knowledge version: ${codexCapabilities.adapterKnowledgeVersion}
Canonical source hash: ${input.canonicalSourceHash}
Artifact hash: ${ARTIFACT_HASH_PLACEHOLDER}
Do not edit; change \`.agent-policy/\` and regenerate.
-->`
}

function skillArtifact(bundle: Bundle, input: ProjectionInput): VirtualArtifact {
  const description = skillDescription(bundle, input)
  const template = `---
name: ${bundle.id}
description: ${JSON.stringify(description)}
---

${generatedHeader(input)}

# ${bundle.id} policy

${renderBundle(bundle, input.resolvedPolicy, 'domain-skill')}
`
  const content = materializeArtifactHash(template)
  return {
    path: `.agents/skills/${bundle.id}/SKILL.md`,
    content,
    sha256: sha256(content),
    owner,
    operation: 'replace',
  }
}

function workflowSkillArtifact(skill: CanonicalWorkflowSkill, input: ProjectionInput): VirtualArtifact {
  const template = `---
name: ${skill.name}
description: ${JSON.stringify(skill.description)}
---

${generatedHeader(input)}

${skill.body}
`
  const content = materializeArtifactHash(template)
  return {
    path: `.agents/skills/${skill.name}/SKILL.md`,
    content,
    sha256: sha256(content),
    owner,
    operation: 'replace',
  }
}

export async function projectCodex(input: ProjectionInput): Promise<readonly VirtualArtifact[]> {
  const content = projectManagedRegion(input.existingArtifacts?.get('AGENTS.md'), rootBody(input))
  const agents: VirtualArtifact = {
    path: 'AGENTS.md',
    content,
    sha256: sha256(content),
    owner,
    operation: 'managed-region',
  }
  const skills = input.resolvedPolicy.bundles
    .filter(({ id }) => id !== 'core')
    .map(({ id }) => {
      const bundle = input.bundles.get(id)
      if (bundle === undefined) throw new Error(`Missing source bundle ${id} for Codex projection`)
      return skillArtifact(bundle, input)
    })
  const workflowSkills = (input.workflowSkills ?? []).map((skill) => workflowSkillArtifact(skill, input))
  return [agents, ...skills, ...workflowSkills]
}

export const codexAdapter = { capabilities: codexCapabilities, project: projectCodex } satisfies HarnessAdapter
