import { mkdtemp, mkdir, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import { scanUnmanagedContent } from '../../src/audit/scan.js'
import { sha256Utf8 } from '../../src/planner/hash.js'
import { validateDocument } from '../../src/schema/validator.js'

describe('Deterministic audit scanner (src/audit/scan.ts)', () => {
  it('scans AGENTS.md with unmanaged sections outside the managed region', async () => {
    const root = await mkdtemp(join(tmpdir(), 'agent-policy-audit-'))

    const agentsContent = [
      '# Project Guidelines',
      '',
      '## Local conventions',
      'Follow local conventions at all times.',
      '',
      '<!-- agent-policy:start owner=@agent-policy/agent-policy-toolkit -->',
      '# Managed Core Policy',
      'Follow core policy.',
      '<!-- agent-policy:end -->',
      '',
      '## Additional Guidelines',
      'Keep functions small.',
      '',
    ].join('\n')

    await writeFile(join(root, 'AGENTS.md'), agentsContent, 'utf8')

    const result = await scanUnmanagedContent(root)

    expect(result.schemaVersion).toBe('v1')
    expect(result.scannedFiles).toEqual(['AGENTS.md'])
    expect(result.unmanagedBlocks).toHaveLength(2)

    const expectedSha256 = sha256Utf8(agentsContent)

    // Block 1: before managed region (lines 1 to 4)
    expect(result.unmanagedBlocks[0]).toEqual({
      id: 'block-1',
      sourcePath: 'AGENTS.md',
      sourceSha256: expectedSha256,
      lineRange: {
        start: 1,
        end: 4,
      },
      content: [
        '# Project Guidelines',
        '',
        '## Local conventions',
        'Follow local conventions at all times.',
      ].join('\n'),
    })

    // Block 2: after managed region (lines 11 to 12)
    expect(result.unmanagedBlocks[1]).toEqual({
      id: 'block-2',
      sourcePath: 'AGENTS.md',
      sourceSha256: expectedSha256,
      lineRange: {
        start: 11,
        end: 12,
      },
      content: [
        '## Additional Guidelines',
        'Keep functions small.',
      ].join('\n'),
    })

    // Validate against schema
    expect(validateDocument('audit-output-v1', result, 'audit-output.json')).toEqual(result)
  })

  it('scans AGENTS.md with only a managed region and returns 0 unmanaged blocks', async () => {
    const root = await mkdtemp(join(tmpdir(), 'agent-policy-audit-'))

    const agentsContent = [
      '<!-- agent-policy:start owner=@agent-policy/agent-policy-toolkit -->',
      '# Managed Core Policy',
      'Follow core policy.',
      '<!-- agent-policy:end -->',
      '',
    ].join('\n')

    await writeFile(join(root, 'AGENTS.md'), agentsContent, 'utf8')

    const result = await scanUnmanagedContent(root)

    expect(result.schemaVersion).toBe('v1')
    expect(result.scannedFiles).toEqual(['AGENTS.md'])
    expect(result.unmanagedBlocks).toEqual([])
    expect(validateDocument('audit-output-v1', result, 'audit-output.json')).toEqual(result)
  })

  it('ignores fully generated files matching generatedOwnership', async () => {
    const root = await mkdtemp(join(tmpdir(), 'agent-policy-audit-'))

    const generatedMarkdown = [
      '<!--',
      'Generated by @agent-policy/agent-policy-toolkit.',
      '-->',
      '# Generated Skill',
    ].join('\n')

    const generatedWithFrontmatter = [
      '---',
      'name: some-skill',
      '---',
      '',
      '<!--',
      'Generated by @agent-policy/agent-policy-toolkit.',
      '-->',
      '# Generated Skill with Frontmatter',
    ].join('\n')

    const generatedJson = JSON.stringify({
      generatedBy: '@agent-policy/agent-policy-toolkit',
      content: 'something',
    })

    await mkdir(join(root, 'docs'), { recursive: true })
    await writeFile(join(root, 'docs', 'generated1.md'), generatedMarkdown, 'utf8')
    await writeFile(join(root, 'docs', 'generated2.md'), generatedWithFrontmatter, 'utf8')
    await writeFile(join(root, 'docs', 'generated3.json'), generatedJson, 'utf8')

    const result = await scanUnmanagedContent(root, {
      paths: ['docs/generated1.md', 'docs/generated2.md', 'docs/generated3.json'],
    })

    expect(result.schemaVersion).toBe('v1')
    expect(result.scannedFiles).toEqual([])
    expect(result.unmanagedBlocks).toEqual([])
    expect(validateDocument('audit-output-v1', result, 'audit-output.json')).toEqual(result)
  })

  it('ignores files inside .agent-policy/', async () => {
    const root = await mkdtemp(join(tmpdir(), 'agent-policy-audit-'))

    await mkdir(join(root, '.agent-policy', 'rules', 'repo'), { recursive: true })
    await writeFile(
      join(root, '.agent-policy', 'policy.yaml'),
      'schemaVersion: v1\ntoolkitVersion: 0.1.0-alpha.2\nbundles: []\ntargets: [codex]\n',
      'utf8',
    )
    await writeFile(
      join(root, '.agent-policy', 'rules', 'repo', 'rule.md'),
      '# Internal Rule\nSome instruction',
      'utf8',
    )

    const result = await scanUnmanagedContent(root, {
      paths: ['.agent-policy/policy.yaml', '.agent-policy/rules/repo/rule.md'],
    })

    expect(result.schemaVersion).toBe('v1')
    expect(result.scannedFiles).toEqual([])
    expect(result.unmanagedBlocks).toEqual([])
    expect(validateDocument('audit-output-v1', result, 'audit-output.json')).toEqual(result)
  })

  it('scans explicit paths passed via options', async () => {
    const root = await mkdtemp(join(tmpdir(), 'agent-policy-audit-'))

    await mkdir(join(root, 'docs', 'agents'), { recursive: true })

    const guideContent = [
      '# Agents Guide',
      '',
      'Always write unit tests first.',
      'Verify before completing.',
    ].join('\n')

    const triageContent = [
      '# Triage Labels',
      '',
      'Use needs-triage for new items.',
    ].join('\n')

    await writeFile(join(root, 'docs', 'agents', 'guide.md'), guideContent, 'utf8')
    await writeFile(join(root, 'docs', 'agents', 'triage.md'), triageContent, 'utf8')

    const result = await scanUnmanagedContent(root, {
      paths: ['docs/agents/guide.md', 'docs/agents/triage.md'],
    })

    expect(result.schemaVersion).toBe('v1')
    expect(result.scannedFiles).toEqual(['docs/agents/guide.md', 'docs/agents/triage.md'])
    expect(result.unmanagedBlocks).toHaveLength(2)

    expect(result.unmanagedBlocks[0]).toEqual({
      id: 'block-1',
      sourcePath: 'docs/agents/guide.md',
      sourceSha256: sha256Utf8(guideContent),
      lineRange: { start: 1, end: 4 },
      content: guideContent,
    })

    expect(result.unmanagedBlocks[1]).toEqual({
      id: 'block-2',
      sourcePath: 'docs/agents/triage.md',
      sourceSha256: sha256Utf8(triageContent),
      lineRange: { start: 1, end: 3 },
      content: triageContent,
    })

    expect(validateDocument('audit-output-v1', result, 'audit-output.json')).toEqual(result)
  })

  it('rejects paths that escape the repository root', async () => {
    const root = await mkdtemp(join(tmpdir(), 'agent-policy-audit-'))

    await expect(
      scanUnmanagedContent(root, {
        paths: ['../outside.md'],
      }),
    ).rejects.toThrow()
  })

  it('handles non-existent default AGENTS.md gracefully by returning empty result', async () => {
    const root = await mkdtemp(join(tmpdir(), 'agent-policy-audit-'))

    const result = await scanUnmanagedContent(root)

    expect(result.schemaVersion).toBe('v1')
    expect(result.scannedFiles).toEqual([])
    expect(result.unmanagedBlocks).toEqual([])
    expect(validateDocument('audit-output-v1', result, 'audit-output.json')).toEqual(result)
  })

  it('deduplicates paths in scannedFiles and does not duplicate unmanaged blocks', async () => {
    const root = await mkdtemp(join(tmpdir(), 'agent-policy-audit-'))

    const agentsContent = [
      '# Project Guidelines',
      'Guideline text.',
    ].join('\n')

    await writeFile(join(root, 'AGENTS.md'), agentsContent, 'utf8')

    const result = await scanUnmanagedContent(root, {
      paths: ['AGENTS.md', './AGENTS.md', 'AGENTS.md'],
    })

    expect(result.schemaVersion).toBe('v1')
    expect(result.scannedFiles).toEqual(['AGENTS.md'])
    expect(result.unmanagedBlocks).toHaveLength(1)
    expect(validateDocument('audit-output-v1', result, 'audit-output.json')).toEqual(result)
  })
})