import { createHash } from 'node:crypto'
import {
  lstat,
  mkdir,
  mkdtemp,
  readFile,
  readdir,
  symlink,
  writeFile,
} from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'

import { describe, expect, it } from 'vitest'

import {
  createChangePlan,
  type PlanRequest,
} from '../../src/planner/create-plan.js'
import { sha256Utf8 } from '../../src/planner/hash.js'
import { inspectArtifact } from '../../src/planner/inspect.js'
import {
  computePlanHash,
  serializeChangePlan,
} from '../../src/planner/serialize-plan.js'
import type { VirtualArtifact } from '../../src/domain/artifacts.js'
import type { ChangePlan } from '../../src/domain/change-plan.js'

const owner = '@agent-policy/agent-policy-toolkit'
const start = `<!-- agent-policy:start owner=${owner} -->`
const end = '<!-- agent-policy:end -->'

function hash(content: string): string {
  return createHash('sha256').update(content, 'utf8').digest('hex')
}

function artifact(
  path: string,
  content: string,
  operation: VirtualArtifact['operation'] = 'replace',
): VirtualArtifact {
  return { path, content, sha256: hash(content), owner, operation }
}

async function sandbox(): Promise<string> {
  return mkdtemp(join(tmpdir(), 'agent-policy-planner-test-'))
}

async function baseRequest(
  repositoryRoot: string,
  planPath: string,
  overrides: Partial<PlanRequest> = {},
): Promise<PlanRequest> {
  await mkdir(join(repositoryRoot, '.agent-policy'), { recursive: true })
  await writeFile(join(repositoryRoot, '.agent-policy/policy.yaml'), 'schemaVersion: v1\n')
  return {
    command: 'update',
    toolkitVersion: '0.1.0-alpha.0',
    repositoryRoot,
    planPath,
    sourcePaths: ['.agent-policy/policy.yaml'],
    desiredArtifacts: [],
    createdAt: '2026-08-12T00:00:00.000Z',
    ...overrides,
  }
}

describe('planner integrity primitives', () => {
  it('hashes UTF-8 bytes with SHA-256', () => {
    expect(sha256Utf8('abc')).toBe(
      'ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad',
    )
    expect(sha256Utf8('\u2713')).toBe(hash('\u2713'))
  })

  it('serializes schema fields canonically and binds the hash to the document without planHash', () => {
    const first = {
      schemaVersion: '1',
      command: 'update',
      toolkitVersion: '0.1.0-alpha.0',
      repositoryRootFingerprint: 'root',
      sourceHashes: { 'z.yaml': 'z', 'a.yaml': 'a' },
      currentArtifactHashes: { 'z.md': 'z', 'a.md': 'a' },
      currentManagedRegionHashes: { 'z.md': 'zr', 'a.md': 'ar' },
      desiredArtifacts: [
        artifact('z.md', 'z\n'),
        artifact('a.md', 'a\n'),
        artifact('Z.md', 'uppercase z\n'),
      ],
      removals: ['z-old.md', 'a-old.md'],
      diagnostics: [
        { code: 'Z', severity: 'warning', message: 'z', path: 'z.md' },
        { code: 'A', severity: 'info', message: 'a', path: 'a.md' },
      ],
      createdAt: '2026-08-12T00:00:00.000Z',
      planHash: '',
    } satisfies ChangePlan
    const second: ChangePlan = {
      ...first,
      sourceHashes: { 'a.yaml': 'a', 'z.yaml': 'z' },
      currentArtifactHashes: { 'a.md': 'a', 'z.md': 'z' },
      currentManagedRegionHashes: { 'a.md': 'ar', 'z.md': 'zr' },
      desiredArtifacts: [...first.desiredArtifacts].reverse(),
      removals: [...first.removals].reverse(),
      diagnostics: [...first.diagnostics].reverse(),
    }
    const planHash = computePlanHash(first)
    const serialized = serializeChangePlan({ ...first, planHash })

    expect(serialized).toBe(serializeChangePlan({ ...second, planHash }))
    expect(serialized.endsWith('\n')).toBe(true)
    expect(serialized.endsWith('\n\n')).toBe(false)
    expect(JSON.parse(serialized)).toMatchObject({
      sourceHashes: { 'a.yaml': 'a', 'z.yaml': 'z' },
      planHash,
    })
    expect(
      (JSON.parse(serialized) as ChangePlan).desiredArtifacts.map(({ path }) => path),
    ).toEqual(['Z.md', 'a.md', 'z.md'])
    expect(planHash).toBe(
      hash(serializeChangePlan({ ...first, planHash: undefined })),
    )
  })
})

describe('read-only artifact inspection', () => {
  it('classifies missing, unmanaged, clean, and managed generated files', async () => {
    const root = await sandbox()
    const desired = artifact(
      '.agents/skills/typescript/SKILL.md',
      '<!--\nGenerated by @agent-policy/agent-policy-toolkit.\n-->\nnew\n',
    )

    await expect(inspectArtifact(root, desired)).resolves.toMatchObject({ state: 'missing' })
    await mkdir(join(root, '.agents/skills/typescript'), { recursive: true })
    await writeFile(
      join(root, desired.path),
      'Hand-written notes mention Generated by @agent-policy/agent-policy-toolkit. in prose.\n',
    )
    await expect(inspectArtifact(root, desired)).resolves.toMatchObject({ state: 'unmanaged' })
    await writeFile(join(root, desired.path), desired.content)
    await expect(inspectArtifact(root, desired)).resolves.toMatchObject({ state: 'clean' })
    await writeFile(
      join(root, desired.path),
      '<!--\nGenerated by @agent-policy/agent-policy-toolkit.\n-->\nold\n',
    )
    await expect(inspectArtifact(root, desired)).resolves.toMatchObject({
      state: 'managed-drift',
    })
  })

  it('recognizes an exact generated ownership header after skill YAML frontmatter', async () => {
    const root = await sandbox()
    const generatedPrefix = `---
name: typescript
description: "TypeScript policy."
---

<!--
Generated by @agent-policy/agent-policy-toolkit.
Toolkit version: 0.1.0-alpha.0
Adapter knowledge version: codex-2026-08-12
Canonical source hash: source-hash
Do not edit; change \`.agent-policy/\` and regenerate.
-->

# typescript policy

`
    const desired = artifact(
      '.agents/skills/typescript/SKILL.md',
      `${generatedPrefix}Use the new guidance.\n`,
    )
    await mkdir(join(root, '.agents/skills/typescript'), { recursive: true })
    await writeFile(join(root, desired.path), `${generatedPrefix}Use the old guidance.\n`)

    await expect(inspectArtifact(root, desired)).resolves.toMatchObject({
      state: 'managed-drift',
    })
  })

  it('compares an owned Managed Region independently from unmanaged text', async () => {
    const root = await sandbox()
    const desired = artifact(
      'AGENTS.md',
      `# changed outside\n\n${start}\npolicy\n${end}\n`,
      'managed-region',
    )

    await writeFile(join(root, 'AGENTS.md'), `# original outside\n\n${start}\npolicy\n${end}\n`)
    await expect(inspectArtifact(root, desired)).resolves.toMatchObject({ state: 'clean' })

    await writeFile(join(root, 'AGENTS.md'), `# original outside\n\n${start}\nedited\n${end}\n`)
    await expect(inspectArtifact(root, desired)).resolves.toMatchObject({
      state: 'managed-drift',
    })

    await writeFile(join(root, 'AGENTS.md'), '<!-- agent-policy:startowner=broken -->\n')
    await expect(inspectArtifact(root, desired)).resolves.toMatchObject({
      state: 'invalid-marker',
    })
  })
})

describe('Change Plan creation', () => {
  it('plans sorted create, replace, delete, and Managed Region operations without changing the repository', async () => {
    const parent = await sandbox()
    const root = join(parent, 'consumer')
    const planPath = join(parent, 'plans', 'change-plan.json')
    await mkdir(join(root, '.agents/skills/old'), { recursive: true })
    await mkdir(join(root, '.agents/skills/testing'), { recursive: true })
    await mkdir(join(root, '.agents/skills/typescript'), { recursive: true })
    await writeFile(join(root, 'AGENTS.md'), '# Team instructions\n')
    const generatedHeader = '<!--\nGenerated by @agent-policy/agent-policy-toolkit.\n-->\n'
    await writeFile(join(root, '.agents/skills/old/SKILL.md'), `${generatedHeader}old\n`)
    await writeFile(join(root, '.agents/skills/testing/SKILL.md'), `${generatedHeader}old\n`)
    await writeFile(join(root, '.agents/skills/typescript/SKILL.md'), `${generatedHeader}same\n`)
    const beforeAgents = await readFile(join(root, 'AGENTS.md'), 'utf8')
    const beforeTesting = await readFile(join(root, '.agents/skills/testing/SKILL.md'), 'utf8')

    const request = await baseRequest(root, planPath, {
      desiredArtifacts: [
        artifact('.agents/skills/typescript/SKILL.md', `${generatedHeader}same\n`),
        artifact('./.agents/skills/react/SKILL.md', `${generatedHeader}react\n`),
        artifact('.agents/skills/testing/SKILL.md', `${generatedHeader}new\n`),
        artifact('AGENTS.md', `# Team instructions\n\n${start}\npolicy\n${end}\n`, 'managed-region'),
      ],
      removals: ['.agents/skills/missing/SKILL.md', '.agents/skills/old/SKILL.md'],
      diagnostics: [
        { code: 'Z', severity: 'warning', message: 'z', path: 'z.md' },
        { code: 'A', severity: 'info', message: 'a', path: 'a.md' },
      ],
    })
    const plan = await createChangePlan(request)

    expect(plan.desiredArtifacts.map(({ path, operation }) => [path, operation])).toEqual([
      ['.agents/skills/react/SKILL.md', 'create'],
      ['.agents/skills/testing/SKILL.md', 'replace'],
      ['AGENTS.md', 'managed-region'],
    ])
    expect(plan.removals).toEqual(['.agents/skills/old/SKILL.md'])
    expect(plan.sourceHashes).toEqual({
      '.agent-policy/policy.yaml': hash('schemaVersion: v1\n'),
    })
    expect(plan.currentArtifactHashes).toEqual({
      '.agents/skills/old/SKILL.md': hash(`${generatedHeader}old\n`),
      '.agents/skills/testing/SKILL.md': hash(`${generatedHeader}old\n`),
      'AGENTS.md': hash('# Team instructions\n'),
    })
    expect(plan.currentManagedRegionHashes).toEqual({})
    expect(plan.diagnostics.map(({ code }) => code)).toEqual(['A', 'Z'])
    expect(plan.planHash).toBe(computePlanHash(plan))
    expect(await readFile(planPath, 'utf8')).toBe(serializeChangePlan(plan))
    expect(await readFile(join(root, 'AGENTS.md'), 'utf8')).toBe(beforeAgents)
    expect(await readFile(join(root, '.agents/skills/testing/SKILL.md'), 'utf8')).toBe(beforeTesting)
    await expect(lstat(join(root, '.agents/skills/react/SKILL.md'))).rejects.toMatchObject({
      code: 'ENOENT',
    })
  })

  it.each([
    ['/absolute.md', 'absolute'],
    ['../escape.md', 'traversal'],
    ['safe/../../escape.md', 'traversal'],
    ['nested\\escape.md', 'backslash'],
  ])('rejects unsafe artifact path %s', async (unsafePath, _case) => {
    const parent = await sandbox()
    const root = join(parent, 'consumer')
    const planPath = join(parent, 'plan.json')
    await mkdir(root)
    const request = await baseRequest(root, planPath, {
      desiredArtifacts: [artifact(unsafePath, 'unsafe\n')],
    })

    await expect(createChangePlan(request)).rejects.toThrow(/artifact path/i)
    await expect(lstat(planPath)).rejects.toMatchObject({ code: 'ENOENT' })
  })

  it('rejects targets that collide after path normalization', async () => {
    const parent = await sandbox()
    const root = join(parent, 'consumer')
    const request = await baseRequest(root, join(parent, 'plan.json'), {
      desiredArtifacts: [artifact('a/./b.md', 'one\n'), artifact('a/b.md', 'two\n')],
    })

    await expect(createChangePlan(request)).rejects.toThrow(/duplicate target/i)
  })

  it('rejects malformed markers in reviewed virtual Managed Region output', async () => {
    const parent = await sandbox()
    const root = join(parent, 'consumer')
    const planPath = join(parent, 'plan.json')
    await mkdir(root)
    const malformed = artifact(
      'AGENTS.md',
      '<!-- agent-policy:start owner=@agent-policy/agent-policy-toolkit -->\nmissing end\n',
      'managed-region',
    )
    const request = await baseRequest(root, planPath, { desiredArtifacts: [malformed] })

    await expect(createChangePlan(request)).rejects.toThrow(/desired.*Managed Region/i)
    await expect(lstat(planPath)).rejects.toMatchObject({ code: 'ENOENT' })
  })

  it('rejects artifact paths that escape through a repository symlink', async () => {
    const parent = await sandbox()
    const root = join(parent, 'consumer')
    const outside = join(parent, 'outside')
    await mkdir(root)
    await mkdir(outside)
    await symlink(outside, join(root, 'linked'))
    const request = await baseRequest(root, join(parent, 'plan.json'), {
      desiredArtifacts: [artifact('linked/escape.md', 'unsafe\n')],
    })

    await expect(createChangePlan(request)).rejects.toThrow(/outside repository|symlink/i)
    await expect(lstat(join(outside, 'escape.md'))).rejects.toMatchObject({ code: 'ENOENT' })
  })

  it('requires an explicit absolute plan path outside the consumer worktree', async () => {
    const parent = await sandbox()
    const root = join(parent, 'consumer')
    await mkdir(root)
    for (const planPath of ['', 'relative-plan.json', join(root, 'plan.json')]) {
      const request = await baseRequest(root, planPath)
      await expect(createChangePlan(request)).rejects.toThrow(/plan path/i)
    }
  })

  it('leaves the repository and existing plan untouched and removes staging after failure', async () => {
    const parent = await sandbox()
    const root = join(parent, 'consumer')
    const plans = join(parent, 'plans')
    const staging = join(parent, 'staging')
    const planPath = join(plans, 'change-plan.json')
    await mkdir(root)
    await mkdir(plans)
    await mkdir(staging)
    await writeFile(planPath, 'reviewed previous plan\n')
    const previousTmpdir = process.env.TMPDIR
    process.env.TMPDIR = staging
    try {
      const bad = artifact('new.md', 'reviewed\n')
      const request = await baseRequest(root, planPath, {
        desiredArtifacts: [{ ...bad, sha256: hash('different\n') }],
      })

      await expect(createChangePlan(request)).rejects.toThrow(/hash/i)
      expect(await readFile(planPath, 'utf8')).toBe('reviewed previous plan\n')
      await expect(lstat(join(root, 'new.md'))).rejects.toMatchObject({ code: 'ENOENT' })
      expect(await readdir(staging)).toEqual([])
    } finally {
      if (previousTmpdir === undefined) delete process.env.TMPDIR
      else process.env.TMPDIR = previousTmpdir
    }
  })
})
